build_ios_task:
  name: buildReactNativeIOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sequoia-xcode:26.2
  build_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source "$HOME/.cargo/env"
    - brew install just protobuf cmake ninja clang-format pnpm
    - cd packages/react-native
    - |
      rustup target add \
        aarch64-apple-ios \
        aarch64-apple-ios-sim \
        x86_64-apple-ios
    - pnpm i
    - pnpm ubrn:ios
  binary_artifacts:
    path: 'packages/react-native/ios/**/*'
  xcframework_artifacts:
    path: 'packages/react-native/PolycentricReactNativeFramework.xcframework/**/*'
