include:
  - local: '.gitlab/ci/setup_images.yml'
  - local: '.gitlab/ci/build_rs_core.yml'
  - local: '.gitlab/ci/build_js_sdks.yml'
  - local: '.gitlab/ci/build_rn_sdk.yml'
  - local: '.gitlab/ci/build_services.yml'
  - local: '.gitlab/ci/build_app.yml'
  - local: '.gitlab/ci/deploy_app.yml'
  - local: '.gitlab/ci/deploy_services.yml'
  - local: '.gitlab/ci/deploy_pages.yml'
  - local: '.gitlab/ci/scan_dependencies.yml'
  - local: '.gitlab/ci/release.yml'
stages:
  - setup
  - check
  - build
  - publish
  - deploy
  - release
  - test
variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  CARGO_TARGET_DIR: ${CI_PROJECT_DIR}/target
default:
  tags:
    - dind_fast
