packages:
  - apps/*
  - packages/*
  - packages/js-browser/examples/*
  - tools/*

catalog:
  '@noble/hashes': ^1.8.0
  typescript: ^5.9.3

linkWorkspacePackages: true

patchedDependencies:
  uniffi-bindgen-react-native@0.31.0-2: patches/uniffi-bindgen-react-native@0.31.0-2.patch
