// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/backup.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PrivateKey } from "./keypair";
import { EventBundle } from "./events";
/**
 * Message to hex-encode and store securely for account recovery.
 *
 * @generated from protobuf message polycentric.v2.IdentityBackup
 */
export interface IdentityBackup {
    /**
     * The hex string of the identity.
     *
     * @generated from protobuf field: string identity_key = 1
     */
    identityKey: string;
    /**
     * The signed events for the canonical identity chain at the time of creating
     * this backup.
     *
     * @generated from protobuf field: repeated polycentric.v2.EventBundle identity_chain = 2
     */
    identityChain: EventBundle[];
    /**
     * The private key corresponding to the recovery public key in the latest
     * identity document.
     *
     * @generated from protobuf field: polycentric.v2.PrivateKey recovery_key = 3
     */
    recoveryKey?: PrivateKey;
}
// @generated message type with reflection information, may provide speed optimized methods
class IdentityBackup$Type extends MessageType<IdentityBackup> {
    constructor() {
        super("polycentric.v2.IdentityBackup", [
            { no: 1, name: "identity_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "identity_chain", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 3, name: "recovery_key", kind: "message", T: () => PrivateKey }
        ]);
    }
    create(value?: PartialMessage<IdentityBackup>): IdentityBackup {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identityKey = "";
        message.identityChain = [];
        if (value !== undefined)
            reflectionMergePartial<IdentityBackup>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityBackup): IdentityBackup {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity_key */ 1:
                    message.identityKey = reader.string();
                    break;
                case /* repeated polycentric.v2.EventBundle identity_chain */ 2:
                    message.identityChain.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* polycentric.v2.PrivateKey recovery_key */ 3:
                    message.recoveryKey = PrivateKey.internalBinaryRead(reader, reader.uint32(), options, message.recoveryKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityBackup, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity_key = 1; */
        if (message.identityKey !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identityKey);
        /* repeated polycentric.v2.EventBundle identity_chain = 2; */
        for (let i = 0; i < message.identityChain.length; i++)
            EventBundle.internalBinaryWrite(message.identityChain[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.PrivateKey recovery_key = 3; */
        if (message.recoveryKey)
            PrivateKey.internalBinaryWrite(message.recoveryKey, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IdentityBackup
 */
export const IdentityBackup = new IdentityBackup$Type();
