// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/common.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message polycentric.v2.PageInfo
 */
export interface PageInfo {
    /**
     * @generated from protobuf field: string end_cursor = 1
     */
    endCursor: string;
    /**
     * @generated from protobuf field: bool has_next_page = 2
     */
    hasNextPage: boolean;
    /**
     * @generated from protobuf field: bool has_previous_page = 3
     */
    hasPreviousPage: boolean;
    /**
     * @generated from protobuf field: string start_cursor = 4
     */
    startCursor: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class PageInfo$Type extends MessageType<PageInfo> {
    constructor() {
        super("polycentric.v2.PageInfo", [
            { no: 1, name: "end_cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "has_next_page", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "has_previous_page", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "start_cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PageInfo>): PageInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.endCursor = "";
        message.hasNextPage = false;
        message.hasPreviousPage = false;
        message.startCursor = "";
        if (value !== undefined)
            reflectionMergePartial<PageInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageInfo): PageInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string end_cursor */ 1:
                    message.endCursor = reader.string();
                    break;
                case /* bool has_next_page */ 2:
                    message.hasNextPage = reader.bool();
                    break;
                case /* bool has_previous_page */ 3:
                    message.hasPreviousPage = reader.bool();
                    break;
                case /* string start_cursor */ 4:
                    message.startCursor = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string end_cursor = 1; */
        if (message.endCursor !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.endCursor);
        /* bool has_next_page = 2; */
        if (message.hasNextPage !== false)
            writer.tag(2, WireType.Varint).bool(message.hasNextPage);
        /* bool has_previous_page = 3; */
        if (message.hasPreviousPage !== false)
            writer.tag(3, WireType.Varint).bool(message.hasPreviousPage);
        /* string start_cursor = 4; */
        if (message.startCursor !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.startCursor);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PageInfo
 */
export const PageInfo = new PageInfo$Type();
