// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/common.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Returned by paginated feeds to aid in future queries.
 *
 * @generated from protobuf message polycentric.v2.PageInfo
 */
export interface PageInfo {
    /**
     * Opaque string that can be included in a request to the server to receive
     * the previous page of data.
     *
     * @generated from protobuf field: string start_cursor = 1
     */
    startCursor: string;
    /**
     * Opaque string that can be included in a request to the server to receive
     * the next page of data.
     *
     * @generated from protobuf field: string end_cursor = 2
     */
    endCursor: string;
    /**
     * True if there is likely more data preceding `start_cursor`.
     *
     * @generated from protobuf field: bool has_previous_page = 3
     */
    hasPreviousPage: boolean;
    /**
     * True if there is likely more data following `end_cursor`.
     *
     * @generated from protobuf field: bool has_next_page = 4
     */
    hasNextPage: boolean;
}
/**
 * Sent by clients to servers for fetching paginated data.
 *
 * @generated from protobuf message polycentric.v2.PageParams
 */
export interface PageParams {
    /**
     * Max events to return.
     *
     * @generated from protobuf field: optional int32 limit = 1
     */
    limit?: number;
    /**
     * Request data preceding this start cursor in the feed.
     *
     * @generated from protobuf field: optional string backward_token = 2
     */
    backwardToken?: string;
    /**
     * Request data following this end cursor in the feed.
     *
     * @generated from protobuf field: optional string forward_token = 3
     */
    forwardToken?: string;
}
/**
 * @generated from protobuf message polycentric.v2.ContentDigest
 */
export interface ContentDigest {
    /**
     * @generated from protobuf field: polycentric.v2.ContentDigestType type = 1
     */
    type: ContentDigestType;
    /**
     * We hash the serialized bytes
     *
     * @generated from protobuf field: bytes value = 2
     */
    value: Uint8Array;
}
/**
 * @generated from protobuf enum polycentric.v2.ContentDigestType
 */
export enum ContentDigestType {
    /**
     * @generated from protobuf enum value: CONTENT_DIGEST_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: CONTENT_DIGEST_TYPE_SHA256 = 1;
     */
    SHA256 = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class PageInfo$Type extends MessageType<PageInfo> {
    constructor() {
        super("polycentric.v2.PageInfo", [
            { no: 1, name: "start_cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "end_cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "has_previous_page", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "has_next_page", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PageInfo>): PageInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.startCursor = "";
        message.endCursor = "";
        message.hasPreviousPage = false;
        message.hasNextPage = false;
        if (value !== undefined)
            reflectionMergePartial<PageInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageInfo): PageInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string start_cursor */ 1:
                    message.startCursor = reader.string();
                    break;
                case /* string end_cursor */ 2:
                    message.endCursor = reader.string();
                    break;
                case /* bool has_previous_page */ 3:
                    message.hasPreviousPage = reader.bool();
                    break;
                case /* bool has_next_page */ 4:
                    message.hasNextPage = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string start_cursor = 1; */
        if (message.startCursor !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.startCursor);
        /* string end_cursor = 2; */
        if (message.endCursor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.endCursor);
        /* bool has_previous_page = 3; */
        if (message.hasPreviousPage !== false)
            writer.tag(3, WireType.Varint).bool(message.hasPreviousPage);
        /* bool has_next_page = 4; */
        if (message.hasNextPage !== false)
            writer.tag(4, WireType.Varint).bool(message.hasNextPage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PageInfo
 */
export const PageInfo = new PageInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageParams$Type extends MessageType<PageParams> {
    constructor() {
        super("polycentric.v2.PageParams", [
            { no: 1, name: "limit", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "backward_token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "forward_token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PageParams>): PageParams {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PageParams>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageParams): PageParams {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int32 limit */ 1:
                    message.limit = reader.int32();
                    break;
                case /* optional string backward_token */ 2:
                    message.backwardToken = reader.string();
                    break;
                case /* optional string forward_token */ 3:
                    message.forwardToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageParams, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int32 limit = 1; */
        if (message.limit !== undefined)
            writer.tag(1, WireType.Varint).int32(message.limit);
        /* optional string backward_token = 2; */
        if (message.backwardToken !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.backwardToken);
        /* optional string forward_token = 3; */
        if (message.forwardToken !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.forwardToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PageParams
 */
export const PageParams = new PageParams$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ContentDigest$Type extends MessageType<ContentDigest> {
    constructor() {
        super("polycentric.v2.ContentDigest", [
            { no: 1, name: "type", kind: "enum", T: () => ["polycentric.v2.ContentDigestType", ContentDigestType, "CONTENT_DIGEST_TYPE_"] },
            { no: 2, name: "value", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ContentDigest>): ContentDigest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.value = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<ContentDigest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ContentDigest): ContentDigest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.ContentDigestType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* bytes value */ 2:
                    message.value = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ContentDigest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.ContentDigestType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* bytes value = 2; */
        if (message.value.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ContentDigest
 */
export const ContentDigest = new ContentDigest$Type();
