// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/content.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ContentService } from "./content";
import type { UrlInfoResponse } from "./content";
import type { UrlInfoRequest } from "./content";
import type { UploadBlobResponse } from "./content";
import type { UploadBlobRequest } from "./content";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SyncContentResponse } from "./content";
import type { SyncContentRequest } from "./content";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service polycentric.v2.ContentService
 */
export interface IContentServiceClient {
    /**
     * Synchronises events from a client to the server
     *
     * @generated from protobuf rpc: SyncContent
     */
    syncContent(input: SyncContentRequest, options?: RpcOptions): UnaryCall<SyncContentRequest, SyncContentResponse>;
    /**
     * Uploads a blob. If the blob is not referenced in a time window, it will be deleted.
     *
     * @generated from protobuf rpc: UploadBlob
     */
    uploadBlob(input: UploadBlobRequest, options?: RpcOptions): UnaryCall<UploadBlobRequest, UploadBlobResponse>;
    /**
     * Fetches a URL server-side and returns its link preview metadata.
     *
     * @generated from protobuf rpc: UrlInfo
     */
    urlInfo(input: UrlInfoRequest, options?: RpcOptions): UnaryCall<UrlInfoRequest, UrlInfoResponse>;
}
/**
 * @generated from protobuf service polycentric.v2.ContentService
 */
export class ContentServiceClient implements IContentServiceClient, ServiceInfo {
    typeName = ContentService.typeName;
    methods = ContentService.methods;
    options = ContentService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Synchronises events from a client to the server
     *
     * @generated from protobuf rpc: SyncContent
     */
    syncContent(input: SyncContentRequest, options?: RpcOptions): UnaryCall<SyncContentRequest, SyncContentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SyncContentRequest, SyncContentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Uploads a blob. If the blob is not referenced in a time window, it will be deleted.
     *
     * @generated from protobuf rpc: UploadBlob
     */
    uploadBlob(input: UploadBlobRequest, options?: RpcOptions): UnaryCall<UploadBlobRequest, UploadBlobResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadBlobRequest, UploadBlobResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Fetches a URL server-side and returns its link preview metadata.
     *
     * @generated from protobuf rpc: UrlInfo
     */
    urlInfo(input: UrlInfoRequest, options?: RpcOptions): UnaryCall<UrlInfoRequest, UrlInfoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UrlInfoRequest, UrlInfoResponse>("unary", this._transport, method, opt, input);
    }
}
