// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/content.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ContentDigest } from "./common";
import { EventKey } from "./event_key";
import { VerificationTarget } from "./verifications";
import { VerificationVerify } from "./verifications";
import { VerificationClaim } from "./verifications";
import { Identity } from "./identity";
/**
 * Content of the event
 *
 * @generated from protobuf message polycentric.v2.Content
 */
export interface Content {
    /**
     * @generated from protobuf oneof: content_body
     */
    contentBody: {
        oneofKind: "post";
        /**
         * @generated from protobuf field: polycentric.v2.Post post = 2
         */
        post: Post;
    } | {
        oneofKind: "delete";
        /**
         * @generated from protobuf field: polycentric.v2.Delete delete = 3
         */
        delete: Delete;
    } | {
        oneofKind: "follow";
        /**
         * @generated from protobuf field: polycentric.v2.Follow follow = 4
         */
        follow: Follow;
    } | {
        oneofKind: "block";
        /**
         * @generated from protobuf field: polycentric.v2.Block block = 5
         */
        block: Block;
    } | {
        oneofKind: "reaction";
        /**
         * @generated from protobuf field: polycentric.v2.Reaction reaction = 6
         */
        reaction: Reaction;
    } | {
        oneofKind: "profileUpdate";
        /**
         * @generated from protobuf field: polycentric.v2.ProfileUpdate profile_update = 7
         */
        profileUpdate: ProfileUpdate;
    } | {
        oneofKind: "identity";
        /**
         * @generated from protobuf field: polycentric.v2.Identity identity = 8
         */
        identity: Identity;
    } | {
        oneofKind: "repost";
        /**
         * @generated from protobuf field: polycentric.v2.Repost repost = 9
         */
        repost: Repost;
    } | {
        oneofKind: "report";
        /**
         * @generated from protobuf field: polycentric.v2.Report report = 10
         */
        report: Report;
    } | {
        oneofKind: "labels";
        /**
         * @generated from protobuf field: polycentric.v2.Labels labels = 11
         */
        labels: Labels;
    } | {
        oneofKind: "verificationClaim";
        /**
         * Verifications (see verifications.proto)
         *
         * @generated from protobuf field: polycentric.v2.VerificationClaim verification_claim = 12
         */
        verificationClaim: VerificationClaim;
    } | {
        oneofKind: "verificationVerify";
        /**
         * @generated from protobuf field: polycentric.v2.VerificationVerify verification_verify = 13
         */
        verificationVerify: VerificationVerify;
    } | {
        oneofKind: "verificationTarget";
        /**
         * @generated from protobuf field: polycentric.v2.VerificationTarget verification_target = 14
         */
        verificationTarget: VerificationTarget;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Serialized content. This is what we do the ContentDigest / Checksum on.
 *
 * @generated from protobuf message polycentric.v2.SerializedContent
 */
export interface SerializedContent {
    /**
     * @generated from protobuf field: bytes content_bytes = 1
     */
    contentBytes: Uint8Array;
}
/**
 * @generated from protobuf message polycentric.v2.Post
 */
export interface Post {
    /**
     * Main text content of the post
     *
     * @generated from protobuf field: string text = 1
     */
    text: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.PostReply reply = 2
     */
    reply?: PostReply;
    /**
     * Multiple images
     *
     * @generated from protobuf field: repeated polycentric.v2.ImageSet images = 3
     */
    images: ImageSet[];
    /**
     * @generated from protobuf field: optional polycentric.v2.EventKey quote = 4
     */
    quote?: EventKey;
    /**
     * Link previews for URLs in the post text
     *
     * @generated from protobuf field: repeated polycentric.v2.Link links = 5
     */
    links: Link[];
}
/**
 * @generated from protobuf message polycentric.v2.PostReply
 */
export interface PostReply {
    /**
     * Initial post in the reply chain.
     *
     * @generated from protobuf field: polycentric.v2.EventKey root = 1
     */
    root?: EventKey;
    /**
     * Post that is being replied to
     *
     * @generated from protobuf field: polycentric.v2.EventKey parent = 2
     */
    parent?: EventKey;
}
/**
 * @generated from protobuf message polycentric.v2.Link
 */
export interface Link {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: string image = 3
     */
    image: string;
    /**
     * @generated from protobuf field: string url = 4
     */
    url: string;
}
/**
 * @generated from protobuf message polycentric.v2.Repost
 */
export interface Repost {
    /**
     * @generated from protobuf field: optional polycentric.v2.EventKey post = 1
     */
    post?: EventKey;
}
/**
 * When processed by a server it should check if the data is referenced by any events
 * If the Content is linked elswhere, the DELETE is ignored and the server should keep the data.
 * If the Content is not linked elsewhere then it can be deleted / purged by the server.
 * Essentially, a DELETE means; Ignore (or forget about) the contents of a previous event.
 *
 * @generated from protobuf message polycentric.v2.Delete
 */
export interface Delete {
    /**
     * Event key to be deleted
     *
     * @generated from protobuf field: polycentric.v2.EventKey event_key = 1
     */
    eventKey?: EventKey;
}
/**
 * @generated from protobuf message polycentric.v2.Follow
 */
export interface Follow {
    /**
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
}
/**
 * @generated from protobuf message polycentric.v2.Block
 */
export interface Block {
    /**
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
}
/**
 * @generated from protobuf message polycentric.v2.Reaction
 */
export interface Reaction {
    /**
     * Key of the event being reacted to
     *
     * @generated from protobuf field: polycentric.v2.EventKey event_key = 1
     */
    eventKey?: EventKey;
    /**
     * Optional emoji
     *
     * @generated from protobuf field: optional string emoji = 2
     */
    emoji?: string;
    /**
     * Upvote = true. Downvote = false.
     *
     * @generated from protobuf field: bool positive = 3
     */
    positive: boolean;
}
/**
 * @generated from protobuf message polycentric.v2.ProfileUpdate
 */
export interface ProfileUpdate {
    /**
     * A friendly display name for the user
     *
     * @generated from protobuf field: optional string name = 1
     */
    name?: string;
    /**
     * Reference to the Blob for the avatar (support multiple different sizes)
     *
     * @generated from protobuf field: optional polycentric.v2.ImageSet avatar = 2
     */
    avatar?: ImageSet;
    /**
     * Reference to the Blob of a banner (support multiple different sizes)
     *
     * @generated from protobuf field: optional polycentric.v2.ImageSet banner = 3
     */
    banner?: ImageSet;
    /**
     * Bio
     *
     * @generated from protobuf field: optional string description = 4
     */
    description?: string;
}
/**
 * If an uploaded Blob is uploaded to the servers Object Storage and not
 * then attached added to the Content repository, the server will delete from Object Storage.
 *
 * @generated from protobuf message polycentric.v2.Blob
 */
export interface Blob {
    /**
     * Digest/Checksum of the blob
     *
     * @generated from protobuf field: polycentric.v2.ContentDigest digest = 1
     */
    digest?: ContentDigest;
    /**
     * @generated from protobuf field: string mime_type = 2
     */
    mimeType: string;
    /**
     * @generated from protobuf field: int64 size = 3
     */
    size: bigint;
}
/**
 * Single image with reference to the blob
 *
 * @generated from protobuf message polycentric.v2.Image
 */
export interface Image {
    /**
     * @generated from protobuf field: polycentric.v2.Blob blob = 1
     */
    blob?: Blob;
    /**
     * @generated from protobuf field: int32 width = 2
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 3
     */
    height: number;
}
/**
 * Collection of different variants of an image
 *
 * @generated from protobuf message polycentric.v2.ImageSet
 */
export interface ImageSet {
    /**
     * @generated from protobuf field: repeated polycentric.v2.Image images = 1
     */
    images: Image[];
}
/**
 * @generated from protobuf message polycentric.v2.Report
 */
export interface Report {
    /**
     * Event that is being reported
     *
     * @generated from protobuf field: polycentric.v2.EventKey event_key = 1
     */
    eventKey?: EventKey;
    /**
     * @generated from protobuf field: polycentric.v2.ReportCategory category = 2
     */
    category: ReportCategory;
    /**
     * @generated from protobuf field: string additional_info = 3
     */
    additionalInfo: string;
}
/**
 * @generated from protobuf message polycentric.v2.Labels
 */
export interface Labels {
    /**
     * Event that is being labeled
     *
     * @generated from protobuf field: polycentric.v2.EventKey event_key = 1
     */
    eventKey?: EventKey;
    /**
     * @generated from protobuf field: repeated string label_values = 2
     */
    labelValues: string[];
}
/**
 * *
 * gRPC requests
 *
 * @generated from protobuf message polycentric.v2.SyncContentRequest
 */
export interface SyncContentRequest {
    /**
     * Digest that was created from the serialized content_bytes
     *
     * @generated from protobuf field: polycentric.v2.ContentDigest digest = 1
     */
    digest?: ContentDigest;
    /**
     * Serialized Content message
     *
     * @generated from protobuf field: bytes content_bytes = 2
     */
    contentBytes: Uint8Array;
}
/**
 * @generated from protobuf message polycentric.v2.SyncContentResponse
 */
export interface SyncContentResponse {
}
/**
 * *
 * Request message for upoading a blob
 *
 * @generated from protobuf message polycentric.v2.UploadBlobRequest
 */
export interface UploadBlobRequest {
    /**
     * Reference message of the blob (mime type, content digest).
     *
     * @generated from protobuf field: polycentric.v2.Blob blob = 1
     */
    blob?: Blob;
    /**
     * Body (content) of the blob
     *
     * @generated from protobuf field: bytes body = 2
     */
    body: Uint8Array;
}
/**
 * @generated from protobuf message polycentric.v2.UploadBlobResponse
 */
export interface UploadBlobResponse {
}
/**
 * *
 * Request message for fetching link metadata for a URL.
 *
 * @generated from protobuf message polycentric.v2.UrlInfoRequest
 */
export interface UrlInfoRequest {
    /**
     * The URL to fetch metadata for.
     *
     * @generated from protobuf field: string url = 1
     */
    url: string;
}
/**
 * *
 * Response for UrlInfo: the fetched link-preview metadata.
 *
 * @generated from protobuf message polycentric.v2.UrlInfoResponse
 */
export interface UrlInfoResponse {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: string image = 3
     */
    image: string;
}
/**
 * @generated from protobuf enum polycentric.v2.ReportCategory
 */
export enum ReportCategory {
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_SPAM = 1;
     */
    SPAM = 1,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_ABUSE = 2;
     */
    ABUSE = 2,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_CHILD_SAFETY = 3;
     */
    CHILD_SAFETY = 3,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_TERRORISM = 4;
     */
    TERRORISM = 4,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_ILLEGAL = 5;
     */
    ILLEGAL = 5,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_COPYRIGHT = 6;
     */
    COPYRIGHT = 6,
    /**
     * @generated from protobuf enum value: REPORT_CATEGORY_SERVER_POLICY = 7;
     */
    SERVER_POLICY = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class Content$Type extends MessageType<Content> {
    constructor() {
        super("polycentric.v2.Content", [
            { no: 2, name: "post", kind: "message", oneof: "contentBody", T: () => Post },
            { no: 3, name: "delete", kind: "message", oneof: "contentBody", T: () => Delete },
            { no: 4, name: "follow", kind: "message", oneof: "contentBody", T: () => Follow },
            { no: 5, name: "block", kind: "message", oneof: "contentBody", T: () => Block },
            { no: 6, name: "reaction", kind: "message", oneof: "contentBody", T: () => Reaction },
            { no: 7, name: "profile_update", kind: "message", oneof: "contentBody", T: () => ProfileUpdate },
            { no: 8, name: "identity", kind: "message", oneof: "contentBody", T: () => Identity },
            { no: 9, name: "repost", kind: "message", oneof: "contentBody", T: () => Repost },
            { no: 10, name: "report", kind: "message", oneof: "contentBody", T: () => Report },
            { no: 11, name: "labels", kind: "message", oneof: "contentBody", T: () => Labels },
            { no: 12, name: "verification_claim", kind: "message", oneof: "contentBody", T: () => VerificationClaim },
            { no: 13, name: "verification_verify", kind: "message", oneof: "contentBody", T: () => VerificationVerify },
            { no: 14, name: "verification_target", kind: "message", oneof: "contentBody", T: () => VerificationTarget }
        ]);
    }
    create(value?: PartialMessage<Content>): Content {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.contentBody = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<Content>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Content): Content {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.Post post */ 2:
                    message.contentBody = {
                        oneofKind: "post",
                        post: Post.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).post)
                    };
                    break;
                case /* polycentric.v2.Delete delete */ 3:
                    message.contentBody = {
                        oneofKind: "delete",
                        delete: Delete.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).delete)
                    };
                    break;
                case /* polycentric.v2.Follow follow */ 4:
                    message.contentBody = {
                        oneofKind: "follow",
                        follow: Follow.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).follow)
                    };
                    break;
                case /* polycentric.v2.Block block */ 5:
                    message.contentBody = {
                        oneofKind: "block",
                        block: Block.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).block)
                    };
                    break;
                case /* polycentric.v2.Reaction reaction */ 6:
                    message.contentBody = {
                        oneofKind: "reaction",
                        reaction: Reaction.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).reaction)
                    };
                    break;
                case /* polycentric.v2.ProfileUpdate profile_update */ 7:
                    message.contentBody = {
                        oneofKind: "profileUpdate",
                        profileUpdate: ProfileUpdate.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).profileUpdate)
                    };
                    break;
                case /* polycentric.v2.Identity identity */ 8:
                    message.contentBody = {
                        oneofKind: "identity",
                        identity: Identity.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).identity)
                    };
                    break;
                case /* polycentric.v2.Repost repost */ 9:
                    message.contentBody = {
                        oneofKind: "repost",
                        repost: Repost.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).repost)
                    };
                    break;
                case /* polycentric.v2.Report report */ 10:
                    message.contentBody = {
                        oneofKind: "report",
                        report: Report.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).report)
                    };
                    break;
                case /* polycentric.v2.Labels labels */ 11:
                    message.contentBody = {
                        oneofKind: "labels",
                        labels: Labels.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).labels)
                    };
                    break;
                case /* polycentric.v2.VerificationClaim verification_claim */ 12:
                    message.contentBody = {
                        oneofKind: "verificationClaim",
                        verificationClaim: VerificationClaim.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).verificationClaim)
                    };
                    break;
                case /* polycentric.v2.VerificationVerify verification_verify */ 13:
                    message.contentBody = {
                        oneofKind: "verificationVerify",
                        verificationVerify: VerificationVerify.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).verificationVerify)
                    };
                    break;
                case /* polycentric.v2.VerificationTarget verification_target */ 14:
                    message.contentBody = {
                        oneofKind: "verificationTarget",
                        verificationTarget: VerificationTarget.internalBinaryRead(reader, reader.uint32(), options, (message.contentBody as any).verificationTarget)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Content, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.Post post = 2; */
        if (message.contentBody.oneofKind === "post")
            Post.internalBinaryWrite(message.contentBody.post, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Delete delete = 3; */
        if (message.contentBody.oneofKind === "delete")
            Delete.internalBinaryWrite(message.contentBody.delete, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Follow follow = 4; */
        if (message.contentBody.oneofKind === "follow")
            Follow.internalBinaryWrite(message.contentBody.follow, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Block block = 5; */
        if (message.contentBody.oneofKind === "block")
            Block.internalBinaryWrite(message.contentBody.block, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Reaction reaction = 6; */
        if (message.contentBody.oneofKind === "reaction")
            Reaction.internalBinaryWrite(message.contentBody.reaction, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.ProfileUpdate profile_update = 7; */
        if (message.contentBody.oneofKind === "profileUpdate")
            ProfileUpdate.internalBinaryWrite(message.contentBody.profileUpdate, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Identity identity = 8; */
        if (message.contentBody.oneofKind === "identity")
            Identity.internalBinaryWrite(message.contentBody.identity, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Repost repost = 9; */
        if (message.contentBody.oneofKind === "repost")
            Repost.internalBinaryWrite(message.contentBody.repost, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Report report = 10; */
        if (message.contentBody.oneofKind === "report")
            Report.internalBinaryWrite(message.contentBody.report, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.Labels labels = 11; */
        if (message.contentBody.oneofKind === "labels")
            Labels.internalBinaryWrite(message.contentBody.labels, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.VerificationClaim verification_claim = 12; */
        if (message.contentBody.oneofKind === "verificationClaim")
            VerificationClaim.internalBinaryWrite(message.contentBody.verificationClaim, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.VerificationVerify verification_verify = 13; */
        if (message.contentBody.oneofKind === "verificationVerify")
            VerificationVerify.internalBinaryWrite(message.contentBody.verificationVerify, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.VerificationTarget verification_target = 14; */
        if (message.contentBody.oneofKind === "verificationTarget")
            VerificationTarget.internalBinaryWrite(message.contentBody.verificationTarget, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Content
 */
export const Content = new Content$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SerializedContent$Type extends MessageType<SerializedContent> {
    constructor() {
        super("polycentric.v2.SerializedContent", [
            { no: 1, name: "content_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SerializedContent>): SerializedContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.contentBytes = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SerializedContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SerializedContent): SerializedContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes content_bytes */ 1:
                    message.contentBytes = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SerializedContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes content_bytes = 1; */
        if (message.contentBytes.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.contentBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SerializedContent
 */
export const SerializedContent = new SerializedContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Post$Type extends MessageType<Post> {
    constructor() {
        super("polycentric.v2.Post", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reply", kind: "message", T: () => PostReply },
            { no: 3, name: "images", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ImageSet },
            { no: 4, name: "quote", kind: "message", T: () => EventKey },
            { no: 5, name: "links", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Link }
        ]);
    }
    create(value?: PartialMessage<Post>): Post {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        message.images = [];
        message.links = [];
        if (value !== undefined)
            reflectionMergePartial<Post>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Post): Post {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                case /* optional polycentric.v2.PostReply reply */ 2:
                    message.reply = PostReply.internalBinaryRead(reader, reader.uint32(), options, message.reply);
                    break;
                case /* repeated polycentric.v2.ImageSet images */ 3:
                    message.images.push(ImageSet.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional polycentric.v2.EventKey quote */ 4:
                    message.quote = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.quote);
                    break;
                case /* repeated polycentric.v2.Link links */ 5:
                    message.links.push(Link.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Post, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        /* optional polycentric.v2.PostReply reply = 2; */
        if (message.reply)
            PostReply.internalBinaryWrite(message.reply, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.ImageSet images = 3; */
        for (let i = 0; i < message.images.length; i++)
            ImageSet.internalBinaryWrite(message.images[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.EventKey quote = 4; */
        if (message.quote)
            EventKey.internalBinaryWrite(message.quote, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.Link links = 5; */
        for (let i = 0; i < message.links.length; i++)
            Link.internalBinaryWrite(message.links[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Post
 */
export const Post = new Post$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostReply$Type extends MessageType<PostReply> {
    constructor() {
        super("polycentric.v2.PostReply", [
            { no: 1, name: "root", kind: "message", T: () => EventKey },
            { no: 2, name: "parent", kind: "message", T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<PostReply>): PostReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PostReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostReply): PostReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey root */ 1:
                    message.root = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.root);
                    break;
                case /* polycentric.v2.EventKey parent */ 2:
                    message.parent = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.parent);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey root = 1; */
        if (message.root)
            EventKey.internalBinaryWrite(message.root, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.EventKey parent = 2; */
        if (message.parent)
            EventKey.internalBinaryWrite(message.parent, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PostReply
 */
export const PostReply = new PostReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Link$Type extends MessageType<Link> {
    constructor() {
        super("polycentric.v2.Link", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Link>): Link {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.description = "";
        message.image = "";
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<Link>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Link): Link {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string image */ 3:
                    message.image = reader.string();
                    break;
                case /* string url */ 4:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Link, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string image = 3; */
        if (message.image !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.image);
        /* string url = 4; */
        if (message.url !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Link
 */
export const Link = new Link$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Repost$Type extends MessageType<Repost> {
    constructor() {
        super("polycentric.v2.Repost", [
            { no: 1, name: "post", kind: "message", T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<Repost>): Repost {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Repost>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Repost): Repost {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional polycentric.v2.EventKey post */ 1:
                    message.post = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.post);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Repost, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional polycentric.v2.EventKey post = 1; */
        if (message.post)
            EventKey.internalBinaryWrite(message.post, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Repost
 */
export const Repost = new Repost$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Delete$Type extends MessageType<Delete> {
    constructor() {
        super("polycentric.v2.Delete", [
            { no: 1, name: "event_key", kind: "message", T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<Delete>): Delete {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Delete>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Delete): Delete {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey event_key */ 1:
                    message.eventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.eventKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Delete, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey event_key = 1; */
        if (message.eventKey)
            EventKey.internalBinaryWrite(message.eventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Delete
 */
export const Delete = new Delete$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Follow$Type extends MessageType<Follow> {
    constructor() {
        super("polycentric.v2.Follow", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Follow>): Follow {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        if (value !== undefined)
            reflectionMergePartial<Follow>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Follow): Follow {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Follow, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Follow
 */
export const Follow = new Follow$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Block$Type extends MessageType<Block> {
    constructor() {
        super("polycentric.v2.Block", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Block>): Block {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        if (value !== undefined)
            reflectionMergePartial<Block>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Block): Block {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Block, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Block
 */
export const Block = new Block$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Reaction$Type extends MessageType<Reaction> {
    constructor() {
        super("polycentric.v2.Reaction", [
            { no: 1, name: "event_key", kind: "message", T: () => EventKey },
            { no: 2, name: "emoji", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "positive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Reaction>): Reaction {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positive = false;
        if (value !== undefined)
            reflectionMergePartial<Reaction>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Reaction): Reaction {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey event_key */ 1:
                    message.eventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.eventKey);
                    break;
                case /* optional string emoji */ 2:
                    message.emoji = reader.string();
                    break;
                case /* bool positive */ 3:
                    message.positive = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Reaction, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey event_key = 1; */
        if (message.eventKey)
            EventKey.internalBinaryWrite(message.eventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional string emoji = 2; */
        if (message.emoji !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.emoji);
        /* bool positive = 3; */
        if (message.positive !== false)
            writer.tag(3, WireType.Varint).bool(message.positive);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Reaction
 */
export const Reaction = new Reaction$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProfileUpdate$Type extends MessageType<ProfileUpdate> {
    constructor() {
        super("polycentric.v2.ProfileUpdate", [
            { no: 1, name: "name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "avatar", kind: "message", T: () => ImageSet },
            { no: 3, name: "banner", kind: "message", T: () => ImageSet },
            { no: 4, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ProfileUpdate>): ProfileUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ProfileUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProfileUpdate): ProfileUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string name */ 1:
                    message.name = reader.string();
                    break;
                case /* optional polycentric.v2.ImageSet avatar */ 2:
                    message.avatar = ImageSet.internalBinaryRead(reader, reader.uint32(), options, message.avatar);
                    break;
                case /* optional polycentric.v2.ImageSet banner */ 3:
                    message.banner = ImageSet.internalBinaryRead(reader, reader.uint32(), options, message.banner);
                    break;
                case /* optional string description */ 4:
                    message.description = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProfileUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string name = 1; */
        if (message.name !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* optional polycentric.v2.ImageSet avatar = 2; */
        if (message.avatar)
            ImageSet.internalBinaryWrite(message.avatar, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.ImageSet banner = 3; */
        if (message.banner)
            ImageSet.internalBinaryWrite(message.banner, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional string description = 4; */
        if (message.description !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ProfileUpdate
 */
export const ProfileUpdate = new ProfileUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Blob$Type extends MessageType<Blob> {
    constructor() {
        super("polycentric.v2.Blob", [
            { no: 1, name: "digest", kind: "message", T: () => ContentDigest },
            { no: 2, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Blob>): Blob {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.mimeType = "";
        message.size = 0n;
        if (value !== undefined)
            reflectionMergePartial<Blob>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Blob): Blob {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.ContentDigest digest */ 1:
                    message.digest = ContentDigest.internalBinaryRead(reader, reader.uint32(), options, message.digest);
                    break;
                case /* string mime_type */ 2:
                    message.mimeType = reader.string();
                    break;
                case /* int64 size */ 3:
                    message.size = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Blob, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.ContentDigest digest = 1; */
        if (message.digest)
            ContentDigest.internalBinaryWrite(message.digest, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string mime_type = 2; */
        if (message.mimeType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.mimeType);
        /* int64 size = 3; */
        if (message.size !== 0n)
            writer.tag(3, WireType.Varint).int64(message.size);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Blob
 */
export const Blob = new Blob$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Image$Type extends MessageType<Image> {
    constructor() {
        super("polycentric.v2.Image", [
            { no: 1, name: "blob", kind: "message", T: () => Blob },
            { no: 2, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Image>): Image {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.width = 0;
        message.height = 0;
        if (value !== undefined)
            reflectionMergePartial<Image>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Image): Image {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.Blob blob */ 1:
                    message.blob = Blob.internalBinaryRead(reader, reader.uint32(), options, message.blob);
                    break;
                case /* int32 width */ 2:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 3:
                    message.height = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Image, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.Blob blob = 1; */
        if (message.blob)
            Blob.internalBinaryWrite(message.blob, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 width = 2; */
        if (message.width !== 0)
            writer.tag(2, WireType.Varint).int32(message.width);
        /* int32 height = 3; */
        if (message.height !== 0)
            writer.tag(3, WireType.Varint).int32(message.height);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Image
 */
export const Image = new Image$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImageSet$Type extends MessageType<ImageSet> {
    constructor() {
        super("polycentric.v2.ImageSet", [
            { no: 1, name: "images", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Image }
        ]);
    }
    create(value?: PartialMessage<ImageSet>): ImageSet {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.images = [];
        if (value !== undefined)
            reflectionMergePartial<ImageSet>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImageSet): ImageSet {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.Image images */ 1:
                    message.images.push(Image.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ImageSet, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.Image images = 1; */
        for (let i = 0; i < message.images.length; i++)
            Image.internalBinaryWrite(message.images[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ImageSet
 */
export const ImageSet = new ImageSet$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Report$Type extends MessageType<Report> {
    constructor() {
        super("polycentric.v2.Report", [
            { no: 1, name: "event_key", kind: "message", T: () => EventKey },
            { no: 2, name: "category", kind: "enum", T: () => ["polycentric.v2.ReportCategory", ReportCategory, "REPORT_CATEGORY_"] },
            { no: 3, name: "additional_info", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Report>): Report {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.category = 0;
        message.additionalInfo = "";
        if (value !== undefined)
            reflectionMergePartial<Report>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Report): Report {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey event_key */ 1:
                    message.eventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.eventKey);
                    break;
                case /* polycentric.v2.ReportCategory category */ 2:
                    message.category = reader.int32();
                    break;
                case /* string additional_info */ 3:
                    message.additionalInfo = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Report, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey event_key = 1; */
        if (message.eventKey)
            EventKey.internalBinaryWrite(message.eventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* polycentric.v2.ReportCategory category = 2; */
        if (message.category !== 0)
            writer.tag(2, WireType.Varint).int32(message.category);
        /* string additional_info = 3; */
        if (message.additionalInfo !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.additionalInfo);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Report
 */
export const Report = new Report$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Labels$Type extends MessageType<Labels> {
    constructor() {
        super("polycentric.v2.Labels", [
            { no: 1, name: "event_key", kind: "message", T: () => EventKey },
            { no: 2, name: "label_values", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Labels>): Labels {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.labelValues = [];
        if (value !== undefined)
            reflectionMergePartial<Labels>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Labels): Labels {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey event_key */ 1:
                    message.eventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.eventKey);
                    break;
                case /* repeated string label_values */ 2:
                    message.labelValues.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Labels, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey event_key = 1; */
        if (message.eventKey)
            EventKey.internalBinaryWrite(message.eventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated string label_values = 2; */
        for (let i = 0; i < message.labelValues.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.labelValues[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Labels
 */
export const Labels = new Labels$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncContentRequest$Type extends MessageType<SyncContentRequest> {
    constructor() {
        super("polycentric.v2.SyncContentRequest", [
            { no: 1, name: "digest", kind: "message", T: () => ContentDigest },
            { no: 2, name: "content_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SyncContentRequest>): SyncContentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.contentBytes = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SyncContentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SyncContentRequest): SyncContentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.ContentDigest digest */ 1:
                    message.digest = ContentDigest.internalBinaryRead(reader, reader.uint32(), options, message.digest);
                    break;
                case /* bytes content_bytes */ 2:
                    message.contentBytes = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SyncContentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.ContentDigest digest = 1; */
        if (message.digest)
            ContentDigest.internalBinaryWrite(message.digest, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bytes content_bytes = 2; */
        if (message.contentBytes.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.contentBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SyncContentRequest
 */
export const SyncContentRequest = new SyncContentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncContentResponse$Type extends MessageType<SyncContentResponse> {
    constructor() {
        super("polycentric.v2.SyncContentResponse", []);
    }
    create(value?: PartialMessage<SyncContentResponse>): SyncContentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SyncContentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SyncContentResponse): SyncContentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SyncContentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SyncContentResponse
 */
export const SyncContentResponse = new SyncContentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadBlobRequest$Type extends MessageType<UploadBlobRequest> {
    constructor() {
        super("polycentric.v2.UploadBlobRequest", [
            { no: 1, name: "blob", kind: "message", T: () => Blob },
            { no: 2, name: "body", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<UploadBlobRequest>): UploadBlobRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.body = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<UploadBlobRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UploadBlobRequest): UploadBlobRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.Blob blob */ 1:
                    message.blob = Blob.internalBinaryRead(reader, reader.uint32(), options, message.blob);
                    break;
                case /* bytes body */ 2:
                    message.body = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UploadBlobRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.Blob blob = 1; */
        if (message.blob)
            Blob.internalBinaryWrite(message.blob, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bytes body = 2; */
        if (message.body.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.body);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.UploadBlobRequest
 */
export const UploadBlobRequest = new UploadBlobRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadBlobResponse$Type extends MessageType<UploadBlobResponse> {
    constructor() {
        super("polycentric.v2.UploadBlobResponse", []);
    }
    create(value?: PartialMessage<UploadBlobResponse>): UploadBlobResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UploadBlobResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UploadBlobResponse): UploadBlobResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UploadBlobResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.UploadBlobResponse
 */
export const UploadBlobResponse = new UploadBlobResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UrlInfoRequest$Type extends MessageType<UrlInfoRequest> {
    constructor() {
        super("polycentric.v2.UrlInfoRequest", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UrlInfoRequest>): UrlInfoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.url = "";
        if (value !== undefined)
            reflectionMergePartial<UrlInfoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UrlInfoRequest): UrlInfoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UrlInfoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.UrlInfoRequest
 */
export const UrlInfoRequest = new UrlInfoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UrlInfoResponse$Type extends MessageType<UrlInfoResponse> {
    constructor() {
        super("polycentric.v2.UrlInfoResponse", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "image", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UrlInfoResponse>): UrlInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.description = "";
        message.image = "";
        if (value !== undefined)
            reflectionMergePartial<UrlInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UrlInfoResponse): UrlInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string image */ 3:
                    message.image = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UrlInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string image = 3; */
        if (message.image !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.image);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.UrlInfoResponse
 */
export const UrlInfoResponse = new UrlInfoResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.ContentService
 */
export const ContentService = new ServiceType("polycentric.v2.ContentService", [
    { name: "SyncContent", options: {}, I: SyncContentRequest, O: SyncContentResponse },
    { name: "UploadBlob", options: {}, I: UploadBlobRequest, O: UploadBlobResponse },
    { name: "UrlInfo", options: {}, I: UrlInfoRequest, O: UrlInfoResponse }
]);
