// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/content.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ContentService } from "./content";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SyncContentResponse } from "./content";
import type { SyncContentRequest } from "./content";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service polycentric.v2.ContentService
 */
export interface IContentServiceClient {
    /**
     * Synchronises events from a client to the server
     *
     * @generated from protobuf rpc: SyncContent
     */
    syncContent(input: SyncContentRequest, options?: RpcOptions): UnaryCall<SyncContentRequest, SyncContentResponse>;
}
/**
 * @generated from protobuf service polycentric.v2.ContentService
 */
export class ContentServiceClient implements IContentServiceClient, ServiceInfo {
    typeName = ContentService.typeName;
    methods = ContentService.methods;
    options = ContentService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Synchronises events from a client to the server
     *
     * @generated from protobuf rpc: SyncContent
     */
    syncContent(input: SyncContentRequest, options?: RpcOptions): UnaryCall<SyncContentRequest, SyncContentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SyncContentRequest, SyncContentResponse>("unary", this._transport, method, opt, input);
    }
}
