// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/events.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PublicKey } from "./keypair";
import { SerializedContent } from "./content";
import { ContentDigest } from "./content";
import { EventKey } from "./event_key";
/**
 * Contains the sequences (of the same event collection) that the current KeyPair is aware of.
 * The order of the sequences is determined by the the keys listed
 *
 * @generated from protobuf message polycentric.v2.VectorClock
 */
export interface VectorClock {
    /**
     * @generated from protobuf field: repeated uint64 sequence = 1
     */
    sequence: bigint[];
}
/**
 * Event messages reference, but do not include, content
 *
 * @generated from protobuf message polycentric.v2.Event
 */
export interface Event {
    /**
     * Key for the event
     *
     * @generated from protobuf field: polycentric.v2.EventKey key = 1
     */
    key?: EventKey;
    /**
     * Reference to the sequence, of the Identity Collection (1), that holds the identity document
     *
     * @generated from protobuf field: uint64 identity_sequence = 2
     */
    identitySequence: bigint;
    /**
     * Vector clock
     *
     * @generated from protobuf field: polycentric.v2.VectorClock vector_clock = 3
     */
    vectorClock?: VectorClock;
    /**
     * Signature of the previous event signed by the same key. Assists in creating
     * immutable collections.
     *
     * @generated from protobuf field: bytes previous_signature = 4
     */
    previousSignature: Uint8Array;
    /**
     * Digest of the content
     *
     * @generated from protobuf field: polycentric.v2.ContentDigest content_digest = 6
     */
    contentDigest?: ContentDigest;
    /**
     * Timestamp, in milliseconds, of when the event was created
     *
     * @generated from protobuf field: uint64 created_at = 7
     */
    createdAt: bigint;
}
/**
 * @generated from protobuf message polycentric.v2.SignedEvent
 */
export interface SignedEvent {
    /**
     * Signature of events_bytes below (not the Event message)
     *
     * @generated from protobuf field: bytes signature = 1
     */
    signature: Uint8Array;
    /**
     * Serialized representation of the Event message that is signed against
     *
     * @generated from protobuf field: bytes event_bytes = 2
     */
    eventBytes: Uint8Array;
}
/**
 * Bundle of the SignedEvent and SerializedContent messages
 * We use SerializedContent so that the checksum of the content
 * can be verified
 *
 * @generated from protobuf message polycentric.v2.EventBundle
 */
export interface EventBundle {
    /**
     * @generated from protobuf field: polycentric.v2.SignedEvent signed_event = 1
     */
    signedEvent?: SignedEvent;
    /**
     * @generated from protobuf field: optional polycentric.v2.SerializedContent serialized_content = 2
     */
    serializedContent?: SerializedContent;
}
/**
 * @generated from protobuf message polycentric.v2.ListEventsFilters
 */
export interface ListEventsFilters {
    /**
     * Collection to filter events by
     *
     * @generated from protobuf field: optional int32 collection = 1
     */
    collection?: number;
    /**
     * Identity key to filter events by
     *
     * @generated from protobuf field: optional string identity = 2
     */
    identity?: string;
    /**
     * Filter events to those signed by this public key
     *
     * @generated from protobuf field: optional polycentric.v2.PublicKey signed_by = 3
     */
    signedBy?: PublicKey;
    /**
     * Return sequences greater than
     *
     * @generated from protobuf field: optional int64 sequence_gt = 4
     */
    sequenceGt?: bigint;
    /**
     * Return sequences less than
     *
     * @generated from protobuf field: optional int64 sequence_lt = 5
     */
    sequenceLt?: bigint;
}
/**
 * @generated from protobuf message polycentric.v2.ListEventsRequest
 */
export interface ListEventsRequest {
    /**
     * Filters
     *
     * @generated from protobuf field: optional polycentric.v2.ListEventsFilters filters = 1
     */
    filters?: ListEventsFilters;
    /**
     * Max number of events to return
     *
     * @generated from protobuf field: optional int32 size = 2
     */
    size?: number;
}
/**
 * @generated from protobuf message polycentric.v2.ListEventsResponse
 */
export interface ListEventsResponse {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
    /**
     * @generated from protobuf field: string previous_token = 2
     */
    previousToken: string;
    /**
     * @generated from protobuf field: string next_token = 3
     */
    nextToken: string;
}
/**
 * @generated from protobuf message polycentric.v2.PutEventsRequest
 */
export interface PutEventsRequest {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
}
/**
 * @generated from protobuf message polycentric.v2.PutEventsResponse
 */
export interface PutEventsResponse {
}
// @generated message type with reflection information, may provide speed optimized methods
class VectorClock$Type extends MessageType<VectorClock> {
    constructor() {
        super("polycentric.v2.VectorClock", [
            { no: 1, name: "sequence", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<VectorClock>): VectorClock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sequence = [];
        if (value !== undefined)
            reflectionMergePartial<VectorClock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VectorClock): VectorClock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated uint64 sequence */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.sequence.push(reader.uint64().toBigInt());
                    else
                        message.sequence.push(reader.uint64().toBigInt());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VectorClock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated uint64 sequence = 1; */
        if (message.sequence.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.sequence.length; i++)
                writer.uint64(message.sequence[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.VectorClock
 */
export const VectorClock = new VectorClock$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Event$Type extends MessageType<Event> {
    constructor() {
        super("polycentric.v2.Event", [
            { no: 1, name: "key", kind: "message", T: () => EventKey },
            { no: 2, name: "identity_sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "vector_clock", kind: "message", T: () => VectorClock },
            { no: 4, name: "previous_signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 6, name: "content_digest", kind: "message", T: () => ContentDigest },
            { no: 7, name: "created_at", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Event>): Event {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identitySequence = 0n;
        message.previousSignature = new Uint8Array(0);
        message.createdAt = 0n;
        if (value !== undefined)
            reflectionMergePartial<Event>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Event): Event {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey key */ 1:
                    message.key = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.key);
                    break;
                case /* uint64 identity_sequence */ 2:
                    message.identitySequence = reader.uint64().toBigInt();
                    break;
                case /* polycentric.v2.VectorClock vector_clock */ 3:
                    message.vectorClock = VectorClock.internalBinaryRead(reader, reader.uint32(), options, message.vectorClock);
                    break;
                case /* bytes previous_signature */ 4:
                    message.previousSignature = reader.bytes();
                    break;
                case /* polycentric.v2.ContentDigest content_digest */ 6:
                    message.contentDigest = ContentDigest.internalBinaryRead(reader, reader.uint32(), options, message.contentDigest);
                    break;
                case /* uint64 created_at */ 7:
                    message.createdAt = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Event, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey key = 1; */
        if (message.key)
            EventKey.internalBinaryWrite(message.key, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* uint64 identity_sequence = 2; */
        if (message.identitySequence !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.identitySequence);
        /* polycentric.v2.VectorClock vector_clock = 3; */
        if (message.vectorClock)
            VectorClock.internalBinaryWrite(message.vectorClock, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bytes previous_signature = 4; */
        if (message.previousSignature.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.previousSignature);
        /* polycentric.v2.ContentDigest content_digest = 6; */
        if (message.contentDigest)
            ContentDigest.internalBinaryWrite(message.contentDigest, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* uint64 created_at = 7; */
        if (message.createdAt !== 0n)
            writer.tag(7, WireType.Varint).uint64(message.createdAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Event
 */
export const Event = new Event$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SignedEvent$Type extends MessageType<SignedEvent> {
    constructor() {
        super("polycentric.v2.SignedEvent", [
            { no: 1, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "event_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SignedEvent>): SignedEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.signature = new Uint8Array(0);
        message.eventBytes = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SignedEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SignedEvent): SignedEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes signature */ 1:
                    message.signature = reader.bytes();
                    break;
                case /* bytes event_bytes */ 2:
                    message.eventBytes = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SignedEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes signature = 1; */
        if (message.signature.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.signature);
        /* bytes event_bytes = 2; */
        if (message.eventBytes.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.eventBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SignedEvent
 */
export const SignedEvent = new SignedEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EventBundle$Type extends MessageType<EventBundle> {
    constructor() {
        super("polycentric.v2.EventBundle", [
            { no: 1, name: "signed_event", kind: "message", T: () => SignedEvent },
            { no: 2, name: "serialized_content", kind: "message", T: () => SerializedContent }
        ]);
    }
    create(value?: PartialMessage<EventBundle>): EventBundle {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<EventBundle>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EventBundle): EventBundle {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SignedEvent signed_event */ 1:
                    message.signedEvent = SignedEvent.internalBinaryRead(reader, reader.uint32(), options, message.signedEvent);
                    break;
                case /* optional polycentric.v2.SerializedContent serialized_content */ 2:
                    message.serializedContent = SerializedContent.internalBinaryRead(reader, reader.uint32(), options, message.serializedContent);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EventBundle, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SignedEvent signed_event = 1; */
        if (message.signedEvent)
            SignedEvent.internalBinaryWrite(message.signedEvent, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.SerializedContent serialized_content = 2; */
        if (message.serializedContent)
            SerializedContent.internalBinaryWrite(message.serializedContent, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.EventBundle
 */
export const EventBundle = new EventBundle$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsFilters$Type extends MessageType<ListEventsFilters> {
    constructor() {
        super("polycentric.v2.ListEventsFilters", [
            { no: 1, name: "collection", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "identity", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "signed_by", kind: "message", T: () => PublicKey },
            { no: 4, name: "sequence_gt", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "sequence_lt", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ListEventsFilters>): ListEventsFilters {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListEventsFilters>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsFilters): ListEventsFilters {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int32 collection */ 1:
                    message.collection = reader.int32();
                    break;
                case /* optional string identity */ 2:
                    message.identity = reader.string();
                    break;
                case /* optional polycentric.v2.PublicKey signed_by */ 3:
                    message.signedBy = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.signedBy);
                    break;
                case /* optional int64 sequence_gt */ 4:
                    message.sequenceGt = reader.int64().toBigInt();
                    break;
                case /* optional int64 sequence_lt */ 5:
                    message.sequenceLt = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsFilters, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int32 collection = 1; */
        if (message.collection !== undefined)
            writer.tag(1, WireType.Varint).int32(message.collection);
        /* optional string identity = 2; */
        if (message.identity !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.identity);
        /* optional polycentric.v2.PublicKey signed_by = 3; */
        if (message.signedBy)
            PublicKey.internalBinaryWrite(message.signedBy, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional int64 sequence_gt = 4; */
        if (message.sequenceGt !== undefined)
            writer.tag(4, WireType.Varint).int64(message.sequenceGt);
        /* optional int64 sequence_lt = 5; */
        if (message.sequenceLt !== undefined)
            writer.tag(5, WireType.Varint).int64(message.sequenceLt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListEventsFilters
 */
export const ListEventsFilters = new ListEventsFilters$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsRequest$Type extends MessageType<ListEventsRequest> {
    constructor() {
        super("polycentric.v2.ListEventsRequest", [
            { no: 1, name: "filters", kind: "message", T: () => ListEventsFilters },
            { no: 2, name: "size", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListEventsRequest>): ListEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsRequest): ListEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional polycentric.v2.ListEventsFilters filters */ 1:
                    message.filters = ListEventsFilters.internalBinaryRead(reader, reader.uint32(), options, message.filters);
                    break;
                case /* optional int32 size */ 2:
                    message.size = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional polycentric.v2.ListEventsFilters filters = 1; */
        if (message.filters)
            ListEventsFilters.internalBinaryWrite(message.filters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional int32 size = 2; */
        if (message.size !== undefined)
            writer.tag(2, WireType.Varint).int32(message.size);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListEventsRequest
 */
export const ListEventsRequest = new ListEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListEventsResponse$Type extends MessageType<ListEventsResponse> {
    constructor() {
        super("polycentric.v2.ListEventsResponse", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 2, name: "previous_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "next_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListEventsResponse>): ListEventsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        message.previousToken = "";
        message.nextToken = "";
        if (value !== undefined)
            reflectionMergePartial<ListEventsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListEventsResponse): ListEventsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string previous_token */ 2:
                    message.previousToken = reader.string();
                    break;
                case /* string next_token */ 3:
                    message.nextToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListEventsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string previous_token = 2; */
        if (message.previousToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.previousToken);
        /* string next_token = 3; */
        if (message.nextToken !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.nextToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListEventsResponse
 */
export const ListEventsResponse = new ListEventsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutEventsRequest$Type extends MessageType<PutEventsRequest> {
    constructor() {
        super("polycentric.v2.PutEventsRequest", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle }
        ]);
    }
    create(value?: PartialMessage<PutEventsRequest>): PutEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        if (value !== undefined)
            reflectionMergePartial<PutEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutEventsRequest): PutEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutEventsRequest
 */
export const PutEventsRequest = new PutEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PutEventsResponse$Type extends MessageType<PutEventsResponse> {
    constructor() {
        super("polycentric.v2.PutEventsResponse", []);
    }
    create(value?: PartialMessage<PutEventsResponse>): PutEventsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PutEventsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PutEventsResponse): PutEventsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PutEventsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PutEventsResponse
 */
export const PutEventsResponse = new PutEventsResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.EventSyncService
 */
export const EventSyncService = new ServiceType("polycentric.v2.EventSyncService", [
    { name: "ListEvents", options: {}, I: ListEventsRequest, O: ListEventsResponse },
    { name: "PutEvents", options: {}, I: PutEventsRequest, O: PutEventsResponse }
]);
