// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/feeds.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FeedsService } from "./feeds";
import type { GetPostThreadResponse } from "./feeds";
import type { GetPostThreadRequest } from "./feeds";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetFeedResponse } from "./feeds";
import type { GetFeedRequest } from "./feeds";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Curated feeds provided by servers
 *
 * @generated from protobuf service polycentric.v2.FeedsService
 */
export interface IFeedsServiceClient {
    /**
     * Returns a curated feed base on the rwquest inputs
     *
     * @generated from protobuf rpc: GetFeed
     */
    getFeed(input: GetFeedRequest, options?: RpcOptions): UnaryCall<GetFeedRequest, GetFeedResponse>;
    /**
     * Replies to a post
     *
     * @generated from protobuf rpc: GetPostThread
     */
    getPostThread(input: GetPostThreadRequest, options?: RpcOptions): UnaryCall<GetPostThreadRequest, GetPostThreadResponse>;
}
/**
 * *
 * Curated feeds provided by servers
 *
 * @generated from protobuf service polycentric.v2.FeedsService
 */
export class FeedsServiceClient implements IFeedsServiceClient, ServiceInfo {
    typeName = FeedsService.typeName;
    methods = FeedsService.methods;
    options = FeedsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Returns a curated feed base on the rwquest inputs
     *
     * @generated from protobuf rpc: GetFeed
     */
    getFeed(input: GetFeedRequest, options?: RpcOptions): UnaryCall<GetFeedRequest, GetFeedResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Replies to a post
     *
     * @generated from protobuf rpc: GetPostThread
     */
    getPostThread(input: GetPostThreadRequest, options?: RpcOptions): UnaryCall<GetPostThreadRequest, GetPostThreadResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostThreadRequest, GetPostThreadResponse>("unary", this._transport, method, opt, input);
    }
}
