// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/feeds.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from '@protobuf-ts/runtime-rpc';
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
import { Event } from './events';
/**
 * @generated from protobuf message polycentric.v2.GetFeedRequest
 */
export interface GetFeedRequest {
  /**
   * @generated from protobuf field: polycentric.v2.FeedAlgorithm algorithm = 1
   */
  algorithm: FeedAlgorithm;
  /**
   * @generated from protobuf field: optional int32 limit = 2
   */
  limit?: number;
  /**
   * @generated from protobuf field: optional string before_token = 3
   */
  beforeToken?: string;
  /**
   * @generated from protobuf field: optional string after_token = 4
   */
  afterToken?: string;
}
/**
 * @generated from protobuf message polycentric.v2.GetFeedResponse
 */
export interface GetFeedResponse {
  /**
   * @generated from protobuf field: repeated polycentric.v2.Event events = 1
   */
  events: Event[];
  /**
   * @generated from protobuf field: string next_token = 2
   */
  nextToken: string;
  /**
   * @generated from protobuf field: string previous_token = 3
   */
  previousToken: string;
}
/**
 * @generated from protobuf enum polycentric.v2.FeedAlgorithm
 */
export enum FeedAlgorithm {
  /**
   * @generated from protobuf enum value: FEED_ALGORITHM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,
  /**
   * @generated from protobuf enum value: FEED_ALGORITHM_LATEST = 1;
   */
  LATEST = 1,
  /**
   * @generated from protobuf enum value: FEED_ALGORITHM_SUGGESTED = 2;
   */
  SUGGESTED = 2,
}
// @generated message type with reflection information, may provide speed optimized methods
class GetFeedRequest$Type extends MessageType<GetFeedRequest> {
  constructor() {
    super('polycentric.v2.GetFeedRequest', [
      {
        no: 1,
        name: 'algorithm',
        kind: 'enum',
        T: () => [
          'polycentric.v2.FeedAlgorithm',
          FeedAlgorithm,
          'FEED_ALGORITHM_',
        ],
      },
      {
        no: 2,
        name: 'limit',
        kind: 'scalar',
        opt: true,
        T: 5 /*ScalarType.INT32*/,
      },
      {
        no: 3,
        name: 'before_token',
        kind: 'scalar',
        opt: true,
        T: 9 /*ScalarType.STRING*/,
      },
      {
        no: 4,
        name: 'after_token',
        kind: 'scalar',
        opt: true,
        T: 9 /*ScalarType.STRING*/,
      },
    ]);
  }
  create(value?: PartialMessage<GetFeedRequest>): GetFeedRequest {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.algorithm = 0;
    if (value !== undefined)
      reflectionMergePartial<GetFeedRequest>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: GetFeedRequest,
  ): GetFeedRequest {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* polycentric.v2.FeedAlgorithm algorithm */ 1:
          message.algorithm = reader.int32();
          break;
        case /* optional int32 limit */ 2:
          message.limit = reader.int32();
          break;
        case /* optional string before_token */ 3:
          message.beforeToken = reader.string();
          break;
        case /* optional string after_token */ 4:
          message.afterToken = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: GetFeedRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* polycentric.v2.FeedAlgorithm algorithm = 1; */
    if (message.algorithm !== 0)
      writer.tag(1, WireType.Varint).int32(message.algorithm);
    /* optional int32 limit = 2; */
    if (message.limit !== undefined)
      writer.tag(2, WireType.Varint).int32(message.limit);
    /* optional string before_token = 3; */
    if (message.beforeToken !== undefined)
      writer.tag(3, WireType.LengthDelimited).string(message.beforeToken);
    /* optional string after_token = 4; */
    if (message.afterToken !== undefined)
      writer.tag(4, WireType.LengthDelimited).string(message.afterToken);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetFeedRequest
 */
export const GetFeedRequest = new GetFeedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFeedResponse$Type extends MessageType<GetFeedResponse> {
  constructor() {
    super('polycentric.v2.GetFeedResponse', [
      {
        no: 1,
        name: 'events',
        kind: 'message',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: () => Event,
      },
      { no: 2, name: 'next_token', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      {
        no: 3,
        name: 'previous_token',
        kind: 'scalar',
        T: 9 /*ScalarType.STRING*/,
      },
    ]);
  }
  create(value?: PartialMessage<GetFeedResponse>): GetFeedResponse {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.events = [];
    message.nextToken = '';
    message.previousToken = '';
    if (value !== undefined)
      reflectionMergePartial<GetFeedResponse>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: GetFeedResponse,
  ): GetFeedResponse {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated polycentric.v2.Event events */ 1:
          message.events.push(
            Event.internalBinaryRead(reader, reader.uint32(), options),
          );
          break;
        case /* string next_token */ 2:
          message.nextToken = reader.string();
          break;
        case /* string previous_token */ 3:
          message.previousToken = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: GetFeedResponse,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* repeated polycentric.v2.Event events = 1; */
    for (let i = 0; i < message.events.length; i++)
      Event.internalBinaryWrite(
        message.events[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string next_token = 2; */
    if (message.nextToken !== '')
      writer.tag(2, WireType.LengthDelimited).string(message.nextToken);
    /* string previous_token = 3; */
    if (message.previousToken !== '')
      writer.tag(3, WireType.LengthDelimited).string(message.previousToken);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetFeedResponse
 */
export const GetFeedResponse = new GetFeedResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.FeedsService
 */
export const FeedsService = new ServiceType('polycentric.v2.FeedsService', [
  { name: 'GetFeed', options: {}, I: GetFeedRequest, O: GetFeedResponse },
]);
