// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/feeds.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FeedsService } from "./feeds";
import type { GetPostThreadResponse } from "./feeds";
import type { GetPostThreadRequest } from "./feeds";
import type { GetExploreFeedRequest } from "./feeds";
import type { GetFollowingFeedRequest } from "./feeds";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetFeedResponse } from "./feeds";
import type { GetIdentityFeedRequest } from "./feeds";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Curated feeds provided by servers
 *
 * @generated from protobuf service polycentric.v2.FeedsService
 */
export interface IFeedsServiceClient {
    /**
     * Posts that belong to an identity
     *
     * @generated from protobuf rpc: GetIdentityFeed
     */
    getIdentityFeed(input: GetIdentityFeedRequest, options?: RpcOptions): UnaryCall<GetIdentityFeedRequest, GetFeedResponse>;
    /**
     * @generated from protobuf rpc: GetFollowingFeed
     */
    getFollowingFeed(input: GetFollowingFeedRequest, options?: RpcOptions): UnaryCall<GetFollowingFeedRequest, GetFeedResponse>;
    /**
     * @generated from protobuf rpc: GetExploreFeed
     */
    getExploreFeed(input: GetExploreFeedRequest, options?: RpcOptions): UnaryCall<GetExploreFeedRequest, GetFeedResponse>;
    /**
     * Replies to a post
     *
     * @generated from protobuf rpc: GetPostThread
     */
    getPostThread(input: GetPostThreadRequest, options?: RpcOptions): UnaryCall<GetPostThreadRequest, GetPostThreadResponse>;
}
/**
 * *
 * Curated feeds provided by servers
 *
 * @generated from protobuf service polycentric.v2.FeedsService
 */
export class FeedsServiceClient implements IFeedsServiceClient, ServiceInfo {
    typeName = FeedsService.typeName;
    methods = FeedsService.methods;
    options = FeedsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Posts that belong to an identity
     *
     * @generated from protobuf rpc: GetIdentityFeed
     */
    getIdentityFeed(input: GetIdentityFeedRequest, options?: RpcOptions): UnaryCall<GetIdentityFeedRequest, GetFeedResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetIdentityFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetFollowingFeed
     */
    getFollowingFeed(input: GetFollowingFeedRequest, options?: RpcOptions): UnaryCall<GetFollowingFeedRequest, GetFeedResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFollowingFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetExploreFeed
     */
    getExploreFeed(input: GetExploreFeedRequest, options?: RpcOptions): UnaryCall<GetExploreFeedRequest, GetFeedResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetExploreFeedRequest, GetFeedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Replies to a post
     *
     * @generated from protobuf rpc: GetPostThread
     */
    getPostThread(input: GetPostThreadRequest, options?: RpcOptions): UnaryCall<GetPostThreadRequest, GetPostThreadResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPostThreadRequest, GetPostThreadResponse>("unary", this._transport, method, opt, input);
    }
}
