// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PageInfo } from "./common";
// *
// The moderation RPCs are authenticated by the caller's bearer JWT
// (see `auth_middleware`): the ban endpoints require a moderator.

/**
 * *
 * IsModerator: no extra fields.
 *
 * @generated from protobuf message polycentric.v2.IsModeratorRequest
 */
export interface IsModeratorRequest {
}
/**
 * @generated from protobuf message polycentric.v2.IsModeratorResponse
 */
export interface IsModeratorResponse {
    /**
     * @generated from protobuf field: bool is_moderator = 1
     */
    isModerator: boolean;
}
/**
 * *
 * SetBanStatus: ban or unban an identity.
 *
 * @generated from protobuf message polycentric.v2.SetBanStatusRequest
 */
export interface SetBanStatusRequest {
    /**
     * Identity key being banned or unbanned.
     *
     * @generated from protobuf field: string target_identity = 1
     */
    targetIdentity: string;
    /**
     * Desired ban state: true to ban, false to unban.
     *
     * @generated from protobuf field: bool banned = 2
     */
    banned: boolean;
}
/**
 * @generated from protobuf message polycentric.v2.SetBanStatusResponse
 */
export interface SetBanStatusResponse {
}
/**
 * *
 * IsBanned: query whether an identity is banned.
 *
 * @generated from protobuf message polycentric.v2.IsBannedRequest
 */
export interface IsBannedRequest {
    /**
     * Identity key being asked about.
     *
     * @generated from protobuf field: string target_identity = 1
     */
    targetIdentity: string;
}
/**
 * @generated from protobuf message polycentric.v2.IsBannedResponse
 */
export interface IsBannedResponse {
    /**
     * @generated from protobuf field: bool is_banned = 1
     */
    isBanned: boolean;
}
/**
 * *
 * ListBans: paginated, optionally filtered list of banned identities.
 *
 * @generated from protobuf message polycentric.v2.ListBansRequest
 */
export interface ListBansRequest {
    /**
     * Max entries to return; the server clamps to its own bounds.
     *
     * @generated from protobuf field: optional uint32 limit = 1
     */
    limit?: number;
    /**
     * Opaque cursor from a previous response's `page_info.end_cursor`.
     *
     * @generated from protobuf field: optional string after = 2
     */
    after?: string;
    /**
     * Case-insensitive prefix filter: keep only identities beginning with
     * this value.
     *
     * @generated from protobuf field: optional string query = 3
     */
    query?: string;
}
/**
 * @generated from protobuf message polycentric.v2.ListBansResponse
 */
export interface ListBansResponse {
    /**
     * Identity keys banned on this server, most recently banned first.
     *
     * @generated from protobuf field: repeated string banned_identities = 1
     */
    bannedIdentities: string[];
    /**
     * @generated from protobuf field: polycentric.v2.PageInfo page_info = 2
     */
    pageInfo?: PageInfo;
}
// @generated message type with reflection information, may provide speed optimized methods
class IsModeratorRequest$Type extends MessageType<IsModeratorRequest> {
    constructor() {
        super("polycentric.v2.IsModeratorRequest", []);
    }
    create(value?: PartialMessage<IsModeratorRequest>): IsModeratorRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<IsModeratorRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsModeratorRequest): IsModeratorRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsModeratorRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IsModeratorRequest
 */
export const IsModeratorRequest = new IsModeratorRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IsModeratorResponse$Type extends MessageType<IsModeratorResponse> {
    constructor() {
        super("polycentric.v2.IsModeratorResponse", [
            { no: 1, name: "is_moderator", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<IsModeratorResponse>): IsModeratorResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isModerator = false;
        if (value !== undefined)
            reflectionMergePartial<IsModeratorResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsModeratorResponse): IsModeratorResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_moderator */ 1:
                    message.isModerator = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsModeratorResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_moderator = 1; */
        if (message.isModerator !== false)
            writer.tag(1, WireType.Varint).bool(message.isModerator);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IsModeratorResponse
 */
export const IsModeratorResponse = new IsModeratorResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetBanStatusRequest$Type extends MessageType<SetBanStatusRequest> {
    constructor() {
        super("polycentric.v2.SetBanStatusRequest", [
            { no: 1, name: "target_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "banned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SetBanStatusRequest>): SetBanStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.targetIdentity = "";
        message.banned = false;
        if (value !== undefined)
            reflectionMergePartial<SetBanStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetBanStatusRequest): SetBanStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string target_identity */ 1:
                    message.targetIdentity = reader.string();
                    break;
                case /* bool banned */ 2:
                    message.banned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetBanStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string target_identity = 1; */
        if (message.targetIdentity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.targetIdentity);
        /* bool banned = 2; */
        if (message.banned !== false)
            writer.tag(2, WireType.Varint).bool(message.banned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SetBanStatusRequest
 */
export const SetBanStatusRequest = new SetBanStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetBanStatusResponse$Type extends MessageType<SetBanStatusResponse> {
    constructor() {
        super("polycentric.v2.SetBanStatusResponse", []);
    }
    create(value?: PartialMessage<SetBanStatusResponse>): SetBanStatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SetBanStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetBanStatusResponse): SetBanStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetBanStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SetBanStatusResponse
 */
export const SetBanStatusResponse = new SetBanStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IsBannedRequest$Type extends MessageType<IsBannedRequest> {
    constructor() {
        super("polycentric.v2.IsBannedRequest", [
            { no: 1, name: "target_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IsBannedRequest>): IsBannedRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.targetIdentity = "";
        if (value !== undefined)
            reflectionMergePartial<IsBannedRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsBannedRequest): IsBannedRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string target_identity */ 1:
                    message.targetIdentity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsBannedRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string target_identity = 1; */
        if (message.targetIdentity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.targetIdentity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IsBannedRequest
 */
export const IsBannedRequest = new IsBannedRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IsBannedResponse$Type extends MessageType<IsBannedResponse> {
    constructor() {
        super("polycentric.v2.IsBannedResponse", [
            { no: 1, name: "is_banned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<IsBannedResponse>): IsBannedResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isBanned = false;
        if (value !== undefined)
            reflectionMergePartial<IsBannedResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsBannedResponse): IsBannedResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_banned */ 1:
                    message.isBanned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsBannedResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_banned = 1; */
        if (message.isBanned !== false)
            writer.tag(1, WireType.Varint).bool(message.isBanned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.IsBannedResponse
 */
export const IsBannedResponse = new IsBannedResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListBansRequest$Type extends MessageType<ListBansRequest> {
    constructor() {
        super("polycentric.v2.ListBansRequest", [
            { no: 1, name: "limit", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "after", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "query", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListBansRequest>): ListBansRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListBansRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListBansRequest): ListBansRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional uint32 limit */ 1:
                    message.limit = reader.uint32();
                    break;
                case /* optional string after */ 2:
                    message.after = reader.string();
                    break;
                case /* optional string query */ 3:
                    message.query = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListBansRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional uint32 limit = 1; */
        if (message.limit !== undefined)
            writer.tag(1, WireType.Varint).uint32(message.limit);
        /* optional string after = 2; */
        if (message.after !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.after);
        /* optional string query = 3; */
        if (message.query !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.query);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListBansRequest
 */
export const ListBansRequest = new ListBansRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListBansResponse$Type extends MessageType<ListBansResponse> {
    constructor() {
        super("polycentric.v2.ListBansResponse", [
            { no: 1, name: "banned_identities", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "page_info", kind: "message", T: () => PageInfo }
        ]);
    }
    create(value?: PartialMessage<ListBansResponse>): ListBansResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bannedIdentities = [];
        if (value !== undefined)
            reflectionMergePartial<ListBansResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListBansResponse): ListBansResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string banned_identities */ 1:
                    message.bannedIdentities.push(reader.string());
                    break;
                case /* polycentric.v2.PageInfo page_info */ 2:
                    message.pageInfo = PageInfo.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListBansResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string banned_identities = 1; */
        for (let i = 0; i < message.bannedIdentities.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.bannedIdentities[i]);
        /* polycentric.v2.PageInfo page_info = 2; */
        if (message.pageInfo)
            PageInfo.internalBinaryWrite(message.pageInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListBansResponse
 */
export const ListBansResponse = new ListBansResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.IdentityService
 */
export const IdentityService = new ServiceType("polycentric.v2.IdentityService", [
    { name: "IsModerator", options: {}, I: IsModeratorRequest, O: IsModeratorResponse },
    { name: "SetBanStatus", options: {}, I: SetBanStatusRequest, O: SetBanStatusResponse },
    { name: "IsBanned", options: {}, I: IsBannedRequest, O: IsBannedResponse },
    { name: "ListBans", options: {}, I: ListBansRequest, O: ListBansResponse }
]);
