// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { IdentityService } from "./identity_service";
import type { ListBansResponse } from "./identity_service";
import type { ListBansRequest } from "./identity_service";
import type { IsBannedResponse } from "./identity_service";
import type { IsBannedRequest } from "./identity_service";
import type { SetBanStatusResponse } from "./identity_service";
import type { SetBanStatusRequest } from "./identity_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { IsModeratorResponse } from "./identity_service";
import type { IsModeratorRequest } from "./identity_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Identity moderation APIs, authenticated by the caller's bearer JWT
 * (see the note above).
 *
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export interface IIdentityServiceClient {
    /**
     * Returns whether the calling identity is a moderator on this server.
     *
     * @generated from protobuf rpc: IsModerator
     */
    isModerator(input: IsModeratorRequest, options?: RpcOptions): UnaryCall<IsModeratorRequest, IsModeratorResponse>;
    /**
     * Bans or unbans an identity on this server.
     *
     * @generated from protobuf rpc: SetBanStatus
     */
    setBanStatus(input: SetBanStatusRequest, options?: RpcOptions): UnaryCall<SetBanStatusRequest, SetBanStatusResponse>;
    /**
     * Returns whether an identity is banned on this server.
     *
     * @generated from protobuf rpc: IsBanned
     */
    isBanned(input: IsBannedRequest, options?: RpcOptions): UnaryCall<IsBannedRequest, IsBannedResponse>;
    /**
     * Lists the identities banned on this server.
     *
     * @generated from protobuf rpc: ListBans
     */
    listBans(input: ListBansRequest, options?: RpcOptions): UnaryCall<ListBansRequest, ListBansResponse>;
}
/**
 * *
 * Identity moderation APIs, authenticated by the caller's bearer JWT
 * (see the note above).
 *
 * @generated from protobuf service polycentric.v2.IdentityService
 */
export class IdentityServiceClient implements IIdentityServiceClient, ServiceInfo {
    typeName = IdentityService.typeName;
    methods = IdentityService.methods;
    options = IdentityService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Returns whether the calling identity is a moderator on this server.
     *
     * @generated from protobuf rpc: IsModerator
     */
    isModerator(input: IsModeratorRequest, options?: RpcOptions): UnaryCall<IsModeratorRequest, IsModeratorResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<IsModeratorRequest, IsModeratorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Bans or unbans an identity on this server.
     *
     * @generated from protobuf rpc: SetBanStatus
     */
    setBanStatus(input: SetBanStatusRequest, options?: RpcOptions): UnaryCall<SetBanStatusRequest, SetBanStatusResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetBanStatusRequest, SetBanStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Returns whether an identity is banned on this server.
     *
     * @generated from protobuf rpc: IsBanned
     */
    isBanned(input: IsBannedRequest, options?: RpcOptions): UnaryCall<IsBannedRequest, IsBannedResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<IsBannedRequest, IsBannedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Lists the identities banned on this server.
     *
     * @generated from protobuf rpc: ListBans
     */
    listBans(input: ListBansRequest, options?: RpcOptions): UnaryCall<ListBansRequest, ListBansResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBansRequest, ListBansResponse>("unary", this._transport, method, opt, input);
    }
}
