// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/identity.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
import { PublicKey } from './keypair';
/**
 * @generated from protobuf message polycentric.v2.Identity
 */
export interface Identity {
  /**
   * Priority ordered list of the rotation keys (public keys that control the identity and
   * can issue new keys)
   *
   * @generated from protobuf field: repeated polycentric.v2.PublicKey rotation_keys = 1
   */
  rotationKeys: PublicKey[];
  /**
   * List of keys that are allowed to sign events (but not change the identity content).
   *
   * @generated from protobuf field: repeated polycentric.v2.PublicKey signing_keys = 2
   */
  signingKeys: PublicKey[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Identity$Type extends MessageType<Identity> {
  constructor() {
    super('polycentric.v2.Identity', [
      {
        no: 1,
        name: 'rotation_keys',
        kind: 'message',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: () => PublicKey,
      },
      {
        no: 2,
        name: 'signing_keys',
        kind: 'message',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: () => PublicKey,
      },
    ]);
  }
  create(value?: PartialMessage<Identity>): Identity {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.rotationKeys = [];
    message.signingKeys = [];
    if (value !== undefined)
      reflectionMergePartial<Identity>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Identity,
  ): Identity {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* repeated polycentric.v2.PublicKey rotation_keys */ 1:
          message.rotationKeys.push(
            PublicKey.internalBinaryRead(reader, reader.uint32(), options),
          );
          break;
        case /* repeated polycentric.v2.PublicKey signing_keys */ 2:
          message.signingKeys.push(
            PublicKey.internalBinaryRead(reader, reader.uint32(), options),
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Identity,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* repeated polycentric.v2.PublicKey rotation_keys = 1; */
    for (let i = 0; i < message.rotationKeys.length; i++)
      PublicKey.internalBinaryWrite(
        message.rotationKeys[i],
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* repeated polycentric.v2.PublicKey signing_keys = 2; */
    for (let i = 0; i < message.signingKeys.length; i++)
      PublicKey.internalBinaryWrite(
        message.signingKeys[i],
        writer.tag(2, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.Identity
 */
export const Identity = new Identity$Type();
