// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/keypair.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
/**
 * PublicKeys signs all events on the polycentric network. There is usually one public key per account, per device.
 *
 * @generated from protobuf message polycentric.v2.PublicKey
 */
export interface PublicKey {
  /**
   * Type of key used. Defaults to ED25519.
   *
   * @generated from protobuf field: polycentric.v2.KeyType key_type = 1
   */
  keyType: KeyType;
  /**
   * Value of the key
   *
   * @generated from protobuf field: bytes key = 2
   */
  key: Uint8Array;
}
/**
 * @generated from protobuf enum polycentric.v2.KeyType
 */
export enum KeyType {
  /**
   * @generated from protobuf enum value: KEY_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,
  /**
   * @generated from protobuf enum value: KEY_TYPE_ED25519 = 1;
   */
  ED25519 = 1,
}
// @generated message type with reflection information, may provide speed optimized methods
class PublicKey$Type extends MessageType<PublicKey> {
  constructor() {
    super('polycentric.v2.PublicKey', [
      {
        no: 1,
        name: 'key_type',
        kind: 'enum',
        T: () => ['polycentric.v2.KeyType', KeyType, 'KEY_TYPE_'],
      },
      { no: 2, name: 'key', kind: 'scalar', T: 12 /*ScalarType.BYTES*/ },
    ]);
  }
  create(value?: PartialMessage<PublicKey>): PublicKey {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.keyType = 0;
    message.key = new Uint8Array(0);
    if (value !== undefined)
      reflectionMergePartial<PublicKey>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: PublicKey,
  ): PublicKey {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* polycentric.v2.KeyType key_type */ 1:
          message.keyType = reader.int32();
          break;
        case /* bytes key */ 2:
          message.key = reader.bytes();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: PublicKey,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* polycentric.v2.KeyType key_type = 1; */
    if (message.keyType !== 0)
      writer.tag(1, WireType.Varint).int32(message.keyType);
    /* bytes key = 2; */
    if (message.key.length)
      writer.tag(2, WireType.LengthDelimited).bytes(message.key);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PublicKey
 */
export const PublicKey = new PublicKey$Type();
