// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/notifications.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { SignedMessage } from "./server";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message polycentric.v2.RegisterPushNotificationRequest
 */
export interface RegisterPushNotificationRequest {
    /**
     * @generated from protobuf field: string service = 1
     */
    service: string;
    /**
     * @generated from protobuf field: string token = 2
     */
    token: string;
}
/**
 * @generated from protobuf message polycentric.v2.RegisterPushNotificationResponse
 */
export interface RegisterPushNotificationResponse {
}
// @generated message type with reflection information, may provide speed optimized methods
class RegisterPushNotificationRequest$Type extends MessageType<RegisterPushNotificationRequest> {
    constructor() {
        super("polycentric.v2.RegisterPushNotificationRequest", [
            { no: 1, name: "service", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterPushNotificationRequest>): RegisterPushNotificationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.service = "";
        message.token = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterPushNotificationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterPushNotificationRequest): RegisterPushNotificationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string service */ 1:
                    message.service = reader.string();
                    break;
                case /* string token */ 2:
                    message.token = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterPushNotificationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string service = 1; */
        if (message.service !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.service);
        /* string token = 2; */
        if (message.token !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.token);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.RegisterPushNotificationRequest
 */
export const RegisterPushNotificationRequest = new RegisterPushNotificationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterPushNotificationResponse$Type extends MessageType<RegisterPushNotificationResponse> {
    constructor() {
        super("polycentric.v2.RegisterPushNotificationResponse", []);
    }
    create(value?: PartialMessage<RegisterPushNotificationResponse>): RegisterPushNotificationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RegisterPushNotificationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterPushNotificationResponse): RegisterPushNotificationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterPushNotificationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.RegisterPushNotificationResponse
 */
export const RegisterPushNotificationResponse = new RegisterPushNotificationResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.NotificationService
 */
export const NotificationService = new ServiceType("polycentric.v2.NotificationService", [
    { name: "RegisterPushNotifications", options: {}, I: SignedMessage, O: RegisterPushNotificationResponse }
]);
