// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/pairing_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PairingService } from "./pairing_service";
import type { JoinPairingSessionResponse } from "./pairing_service";
import type { JoinPairingSessionRequest } from "./pairing_service";
import type { GetPairingSessionResponse } from "./pairing_service";
import type { GetPairingSessionRequest } from "./pairing_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreatePairingSessionResponse } from "./pairing_service";
import type { CreatePairingSessionRequest } from "./pairing_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * *
 * Pairing APIs used for device pairing.
 *
 * @generated from protobuf service polycentric.v2.PairingService
 */
export interface IPairingServiceClient {
    /**
     * Creates a session after validating the issuer signature and authorization.
     *
     * @generated from protobuf rpc: CreatePairingSession
     */
    createPairingSession(input: CreatePairingSessionRequest, options?: RpcOptions): UnaryCall<CreatePairingSessionRequest, CreatePairingSessionResponse>;
    /**
     * Returns a pairing session for an active session signature.
     *
     * @generated from protobuf rpc: GetPairingSession
     */
    getPairingSession(input: GetPairingSessionRequest, options?: RpcOptions): UnaryCall<GetPairingSessionRequest, GetPairingSessionResponse>;
    /**
     * Registers a claimer for a valid session signature.
     *
     * @generated from protobuf rpc: JoinPairingSession
     */
    joinPairingSession(input: JoinPairingSessionRequest, options?: RpcOptions): UnaryCall<JoinPairingSessionRequest, JoinPairingSessionResponse>;
}
/**
 * *
 * Pairing APIs used for device pairing.
 *
 * @generated from protobuf service polycentric.v2.PairingService
 */
export class PairingServiceClient implements IPairingServiceClient, ServiceInfo {
    typeName = PairingService.typeName;
    methods = PairingService.methods;
    options = PairingService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Creates a session after validating the issuer signature and authorization.
     *
     * @generated from protobuf rpc: CreatePairingSession
     */
    createPairingSession(input: CreatePairingSessionRequest, options?: RpcOptions): UnaryCall<CreatePairingSessionRequest, CreatePairingSessionResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePairingSessionRequest, CreatePairingSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Returns a pairing session for an active session signature.
     *
     * @generated from protobuf rpc: GetPairingSession
     */
    getPairingSession(input: GetPairingSessionRequest, options?: RpcOptions): UnaryCall<GetPairingSessionRequest, GetPairingSessionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPairingSessionRequest, GetPairingSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Registers a claimer for a valid session signature.
     *
     * @generated from protobuf rpc: JoinPairingSession
     */
    joinPairingSession(input: JoinPairingSessionRequest, options?: RpcOptions): UnaryCall<JoinPairingSessionRequest, JoinPairingSessionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<JoinPairingSessionRequest, JoinPairingSessionResponse>("unary", this._transport, method, opt, input);
    }
}
