// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/pairing_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SignedMessage } from "./server";
import { PublicKey } from "./keypair";
/**
 * *
 * Issuer-signed payload for creating a pairing session.
 *
 * @generated from protobuf message polycentric.v2.InitialPairingSession
 */
export interface InitialPairingSession {
    /**
     * Identity key the session is created for.
     *
     * @generated from protobuf field: string issuer_identity = 1
     */
    issuerIdentity: string;
    /**
     * Timestamp so that the pairing session id is unique.
     *
     * @generated from protobuf field: int64 timestamp = 2
     */
    timestamp: bigint;
}
/**
 * *
 * Payload that claimers sign when attempting to join a pairing session.
 *
 * @generated from protobuf message polycentric.v2.JoinPairingSessionBody
 */
export interface JoinPairingSessionBody {
    /**
     * @generated from protobuf field: string pairing_session_signature = 1
     */
    pairingSessionSignature: string;
}
/**
 * *
 * Pairing session stored and returned by the server.
 *
 * @generated from protobuf message polycentric.v2.PairingSession
 */
export interface PairingSession {
    /**
     * Signature of the signed InitialPairingSession payload; serves as the session id.
     *
     * @generated from protobuf field: string pairing_session_signature = 1
     */
    pairingSessionSignature: string;
    /**
     * Public key that signed the InitialPairingSession payload.
     *
     * @generated from protobuf field: polycentric.v2.PublicKey signed_by = 2
     */
    signedBy?: PublicKey;
    /**
     * Identity key the session was created for.
     *
     * @generated from protobuf field: string issuer_identity = 3
     */
    issuerIdentity: string;
    /**
     * Expiration timestamp in unix milliseconds.
     *
     * @generated from protobuf field: int64 expires_at = 4
     */
    expiresAt: bigint;
    /**
     * Public keys that have joined the session so far.
     *
     * @generated from protobuf field: repeated polycentric.v2.PublicKey claimer_pubkeys = 5
     */
    claimerPubkeys: PublicKey[];
    /**
     * Server-authoritative creation timestamp in unix milliseconds.
     *
     * @generated from protobuf field: int64 created_at = 6
     */
    createdAt: bigint;
}
/**
 * *
 * Request payload for fetching a pairing session by signature.
 *
 * @generated from protobuf message polycentric.v2.GetPairingSessionRequest
 */
export interface GetPairingSessionRequest {
    /**
     * @generated from protobuf field: string pairing_session_signature = 1
     */
    pairingSessionSignature: string;
}
/**
 * *
 * Wrapper request for CreatePairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.CreatePairingSessionRequest
 */
export interface CreatePairingSessionRequest {
    /**
     * @generated from protobuf field: polycentric.v2.SignedMessage signed_message = 1
     */
    signedMessage?: SignedMessage;
}
/**
 * *
 * Wrapper response for CreatePairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.CreatePairingSessionResponse
 */
export interface CreatePairingSessionResponse {
    /**
     * @generated from protobuf field: polycentric.v2.PairingSession session = 1
     */
    session?: PairingSession;
}
/**
 * *
 * Wrapper response for GetPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.GetPairingSessionResponse
 */
export interface GetPairingSessionResponse {
    /**
     * @generated from protobuf field: polycentric.v2.PairingSession session = 1
     */
    session?: PairingSession;
}
/**
 * *
 * Wrapper request for JoinPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.JoinPairingSessionRequest
 */
export interface JoinPairingSessionRequest {
    /**
     * @generated from protobuf field: polycentric.v2.SignedMessage signed_message = 1
     */
    signedMessage?: SignedMessage;
}
/**
 * *
 * Wrapper response for JoinPairingSession RPC.
 *
 * @generated from protobuf message polycentric.v2.JoinPairingSessionResponse
 */
export interface JoinPairingSessionResponse {
    /**
     * @generated from protobuf field: polycentric.v2.PairingSession session = 1
     */
    session?: PairingSession;
}
// @generated message type with reflection information, may provide speed optimized methods
class InitialPairingSession$Type extends MessageType<InitialPairingSession> {
    constructor() {
        super("polycentric.v2.InitialPairingSession", [
            { no: 1, name: "issuer_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<InitialPairingSession>): InitialPairingSession {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.issuerIdentity = "";
        message.timestamp = 0n;
        if (value !== undefined)
            reflectionMergePartial<InitialPairingSession>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitialPairingSession): InitialPairingSession {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string issuer_identity */ 1:
                    message.issuerIdentity = reader.string();
                    break;
                case /* int64 timestamp */ 2:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitialPairingSession, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string issuer_identity = 1; */
        if (message.issuerIdentity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.issuerIdentity);
        /* int64 timestamp = 2; */
        if (message.timestamp !== 0n)
            writer.tag(2, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.InitialPairingSession
 */
export const InitialPairingSession = new InitialPairingSession$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinPairingSessionBody$Type extends MessageType<JoinPairingSessionBody> {
    constructor() {
        super("polycentric.v2.JoinPairingSessionBody", [
            { no: 1, name: "pairing_session_signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<JoinPairingSessionBody>): JoinPairingSessionBody {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pairingSessionSignature = "";
        if (value !== undefined)
            reflectionMergePartial<JoinPairingSessionBody>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinPairingSessionBody): JoinPairingSessionBody {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string pairing_session_signature */ 1:
                    message.pairingSessionSignature = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinPairingSessionBody, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string pairing_session_signature = 1; */
        if (message.pairingSessionSignature !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.pairingSessionSignature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.JoinPairingSessionBody
 */
export const JoinPairingSessionBody = new JoinPairingSessionBody$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PairingSession$Type extends MessageType<PairingSession> {
    constructor() {
        super("polycentric.v2.PairingSession", [
            { no: 1, name: "pairing_session_signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "signed_by", kind: "message", T: () => PublicKey },
            { no: 3, name: "issuer_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "expires_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "claimer_pubkeys", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PublicKey },
            { no: 6, name: "created_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<PairingSession>): PairingSession {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pairingSessionSignature = "";
        message.issuerIdentity = "";
        message.expiresAt = 0n;
        message.claimerPubkeys = [];
        message.createdAt = 0n;
        if (value !== undefined)
            reflectionMergePartial<PairingSession>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PairingSession): PairingSession {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string pairing_session_signature */ 1:
                    message.pairingSessionSignature = reader.string();
                    break;
                case /* polycentric.v2.PublicKey signed_by */ 2:
                    message.signedBy = PublicKey.internalBinaryRead(reader, reader.uint32(), options, message.signedBy);
                    break;
                case /* string issuer_identity */ 3:
                    message.issuerIdentity = reader.string();
                    break;
                case /* int64 expires_at */ 4:
                    message.expiresAt = reader.int64().toBigInt();
                    break;
                case /* repeated polycentric.v2.PublicKey claimer_pubkeys */ 5:
                    message.claimerPubkeys.push(PublicKey.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int64 created_at */ 6:
                    message.createdAt = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PairingSession, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string pairing_session_signature = 1; */
        if (message.pairingSessionSignature !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.pairingSessionSignature);
        /* polycentric.v2.PublicKey signed_by = 2; */
        if (message.signedBy)
            PublicKey.internalBinaryWrite(message.signedBy, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string issuer_identity = 3; */
        if (message.issuerIdentity !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.issuerIdentity);
        /* int64 expires_at = 4; */
        if (message.expiresAt !== 0n)
            writer.tag(4, WireType.Varint).int64(message.expiresAt);
        /* repeated polycentric.v2.PublicKey claimer_pubkeys = 5; */
        for (let i = 0; i < message.claimerPubkeys.length; i++)
            PublicKey.internalBinaryWrite(message.claimerPubkeys[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* int64 created_at = 6; */
        if (message.createdAt !== 0n)
            writer.tag(6, WireType.Varint).int64(message.createdAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.PairingSession
 */
export const PairingSession = new PairingSession$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPairingSessionRequest$Type extends MessageType<GetPairingSessionRequest> {
    constructor() {
        super("polycentric.v2.GetPairingSessionRequest", [
            { no: 1, name: "pairing_session_signature", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPairingSessionRequest>): GetPairingSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pairingSessionSignature = "";
        if (value !== undefined)
            reflectionMergePartial<GetPairingSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPairingSessionRequest): GetPairingSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string pairing_session_signature */ 1:
                    message.pairingSessionSignature = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPairingSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string pairing_session_signature = 1; */
        if (message.pairingSessionSignature !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.pairingSessionSignature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPairingSessionRequest
 */
export const GetPairingSessionRequest = new GetPairingSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePairingSessionRequest$Type extends MessageType<CreatePairingSessionRequest> {
    constructor() {
        super("polycentric.v2.CreatePairingSessionRequest", [
            { no: 1, name: "signed_message", kind: "message", T: () => SignedMessage }
        ]);
    }
    create(value?: PartialMessage<CreatePairingSessionRequest>): CreatePairingSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreatePairingSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePairingSessionRequest): CreatePairingSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SignedMessage signed_message */ 1:
                    message.signedMessage = SignedMessage.internalBinaryRead(reader, reader.uint32(), options, message.signedMessage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePairingSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SignedMessage signed_message = 1; */
        if (message.signedMessage)
            SignedMessage.internalBinaryWrite(message.signedMessage, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.CreatePairingSessionRequest
 */
export const CreatePairingSessionRequest = new CreatePairingSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreatePairingSessionResponse$Type extends MessageType<CreatePairingSessionResponse> {
    constructor() {
        super("polycentric.v2.CreatePairingSessionResponse", [
            { no: 1, name: "session", kind: "message", T: () => PairingSession }
        ]);
    }
    create(value?: PartialMessage<CreatePairingSessionResponse>): CreatePairingSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreatePairingSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreatePairingSessionResponse): CreatePairingSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PairingSession session */ 1:
                    message.session = PairingSession.internalBinaryRead(reader, reader.uint32(), options, message.session);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreatePairingSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PairingSession session = 1; */
        if (message.session)
            PairingSession.internalBinaryWrite(message.session, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.CreatePairingSessionResponse
 */
export const CreatePairingSessionResponse = new CreatePairingSessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPairingSessionResponse$Type extends MessageType<GetPairingSessionResponse> {
    constructor() {
        super("polycentric.v2.GetPairingSessionResponse", [
            { no: 1, name: "session", kind: "message", T: () => PairingSession }
        ]);
    }
    create(value?: PartialMessage<GetPairingSessionResponse>): GetPairingSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPairingSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPairingSessionResponse): GetPairingSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PairingSession session */ 1:
                    message.session = PairingSession.internalBinaryRead(reader, reader.uint32(), options, message.session);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPairingSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PairingSession session = 1; */
        if (message.session)
            PairingSession.internalBinaryWrite(message.session, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetPairingSessionResponse
 */
export const GetPairingSessionResponse = new GetPairingSessionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinPairingSessionRequest$Type extends MessageType<JoinPairingSessionRequest> {
    constructor() {
        super("polycentric.v2.JoinPairingSessionRequest", [
            { no: 1, name: "signed_message", kind: "message", T: () => SignedMessage }
        ]);
    }
    create(value?: PartialMessage<JoinPairingSessionRequest>): JoinPairingSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<JoinPairingSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinPairingSessionRequest): JoinPairingSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SignedMessage signed_message */ 1:
                    message.signedMessage = SignedMessage.internalBinaryRead(reader, reader.uint32(), options, message.signedMessage);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinPairingSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SignedMessage signed_message = 1; */
        if (message.signedMessage)
            SignedMessage.internalBinaryWrite(message.signedMessage, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.JoinPairingSessionRequest
 */
export const JoinPairingSessionRequest = new JoinPairingSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinPairingSessionResponse$Type extends MessageType<JoinPairingSessionResponse> {
    constructor() {
        super("polycentric.v2.JoinPairingSessionResponse", [
            { no: 1, name: "session", kind: "message", T: () => PairingSession }
        ]);
    }
    create(value?: PartialMessage<JoinPairingSessionResponse>): JoinPairingSessionResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<JoinPairingSessionResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinPairingSessionResponse): JoinPairingSessionResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.PairingSession session */ 1:
                    message.session = PairingSession.internalBinaryRead(reader, reader.uint32(), options, message.session);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinPairingSessionResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.PairingSession session = 1; */
        if (message.session)
            PairingSession.internalBinaryWrite(message.session, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.JoinPairingSessionResponse
 */
export const JoinPairingSessionResponse = new JoinPairingSessionResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.PairingService
 */
export const PairingService = new ServiceType("polycentric.v2.PairingService", [
    { name: "CreatePairingSession", options: {}, I: CreatePairingSessionRequest, O: CreatePairingSessionResponse },
    { name: "GetPairingSession", options: {}, I: GetPairingSessionRequest, O: GetPairingSessionResponse },
    { name: "JoinPairingSession", options: {}, I: JoinPairingSessionRequest, O: JoinPairingSessionResponse }
]);
