// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/profile_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ProfileService } from "./profile_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetProfileResponse } from "./profile_service";
import type { GetProfileRequest } from "./profile_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service polycentric.v2.ProfileService
 */
export interface IProfileServiceClient {
    /**
     * A profile with its aggregate counters.
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse>;
}
/**
 * @generated from protobuf service polycentric.v2.ProfileService
 */
export class ProfileServiceClient implements IProfileServiceClient, ServiceInfo {
    typeName = ProfileService.typeName;
    methods = ProfileService.methods;
    options = ProfileService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * A profile with its aggregate counters.
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfileRequest, GetProfileResponse>("unary", this._transport, method, opt, input);
    }
}
