// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/profile_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { EventHint } from "./events";
import { EventBundle } from "./events";
/**
 * @generated from protobuf message polycentric.v2.GetProfileRequest
 */
export interface GetProfileRequest {
    /**
     * @generated from protobuf field: string identity = 1
     */
    identity: string;
}
/**
 * @generated from protobuf message polycentric.v2.GetProfileResponse
 */
export interface GetProfileResponse {
    /**
     * The identity's latest profile events.
     *
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
    /**
     * Side information needed to validate the bundles (the identity's
     * key chain).
     *
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 2
     */
    eventHints: EventHint[];
    /**
     * Distinct identities this identity follows.
     *
     * @generated from protobuf field: uint64 following_count = 3
     */
    followingCount: bigint;
    /**
     * Distinct identities following this identity.
     *
     * @generated from protobuf field: uint64 followers_count = 4
     */
    followersCount: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetProfileRequest$Type extends MessageType<GetProfileRequest> {
    constructor() {
        super("polycentric.v2.GetProfileRequest", [
            { no: 1, name: "identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetProfileRequest>): GetProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.identity = "";
        if (value !== undefined)
            reflectionMergePartial<GetProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProfileRequest): GetProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string identity */ 1:
                    message.identity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string identity = 1; */
        if (message.identity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.identity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetProfileRequest
 */
export const GetProfileRequest = new GetProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProfileResponse$Type extends MessageType<GetProfileResponse> {
    constructor() {
        super("polycentric.v2.GetProfileResponse", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle },
            { no: 2, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint },
            { no: 3, name: "following_count", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "followers_count", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<GetProfileResponse>): GetProfileResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        message.eventHints = [];
        message.followingCount = 0n;
        message.followersCount = 0n;
        if (value !== undefined)
            reflectionMergePartial<GetProfileResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProfileResponse): GetProfileResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 2:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* uint64 following_count */ 3:
                    message.followingCount = reader.uint64().toBigInt();
                    break;
                case /* uint64 followers_count */ 4:
                    message.followersCount = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProfileResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 2; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* uint64 following_count = 3; */
        if (message.followingCount !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.followingCount);
        /* uint64 followers_count = 4; */
        if (message.followersCount !== 0n)
            writer.tag(4, WireType.Varint).uint64(message.followersCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetProfileResponse
 */
export const GetProfileResponse = new GetProfileResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.ProfileService
 */
export const ProfileService = new ServiceType("polycentric.v2.ProfileService", [
    { name: "GetProfile", options: {}, I: GetProfileRequest, O: GetProfileResponse }
]);
