// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/search.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { EventBundle } from "./events";
import { EventHint } from "./events";
import { PageInfo } from "./common";
import { PageParams } from "./common";
/**
 * @generated from protobuf message polycentric.v2.SearchUsersRequest
 */
export interface SearchUsersRequest {
    /**
     * @generated from protobuf field: string query = 1
     */
    query: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.SortUsersBy sort_by = 2
     */
    sortBy?: SortUsersBy;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 3
     */
    pageParams?: PageParams;
}
/**
 * @generated from protobuf message polycentric.v2.SearchPostsRequest
 */
export interface SearchPostsRequest {
    /**
     * @generated from protobuf field: string query = 1
     */
    query: string;
    /**
     * @generated from protobuf field: optional polycentric.v2.SortPostsBy sort_by = 2
     */
    sortBy?: SortPostsBy;
    /**
     * @generated from protobuf field: optional polycentric.v2.PageParams page_params = 3
     */
    pageParams?: PageParams;
    /**
     * Label values for which the requester does not want to see content.
     *
     * @generated from protobuf field: repeated string omit_labels = 4
     */
    omitLabels: string[];
}
// TODO: add additional data for why events are returned.

/**
 * @generated from protobuf message polycentric.v2.SearchUsersResponse
 */
export interface SearchUsersResponse {
    /**
     * Relevant search results.
     *
     * @generated from protobuf field: repeated polycentric.v2.SearchResult results = 1
     */
    results: SearchResult[];
    /**
     * @generated from protobuf field: optional polycentric.v2.PageInfo page_info = 2
     */
    pageInfo?: PageInfo;
    /**
     * Relevant events for the events in the search results.
     *
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 3
     */
    eventHints: EventHint[];
}
/**
 * @generated from protobuf message polycentric.v2.SearchPostsResponse
 */
export interface SearchPostsResponse {
    /**
     * Relevant search results.
     *
     * @generated from protobuf field: repeated polycentric.v2.SearchResult results = 1
     */
    results: SearchResult[];
    /**
     * @generated from protobuf field: optional polycentric.v2.PageInfo page_info = 2
     */
    pageInfo?: PageInfo;
    /**
     * Relevant events for the events in the search results.
     *
     * @generated from protobuf field: repeated polycentric.v2.EventHint event_hints = 3
     */
    eventHints: EventHint[];
}
/**
 * @generated from protobuf message polycentric.v2.SearchResult
 */
export interface SearchResult {
    /**
     * @generated from protobuf field: polycentric.v2.EventBundle event_bundle = 1
     */
    eventBundle?: EventBundle;
    /**
     * Search rank, higher means more relevant.
     *
     * @generated from protobuf field: float rank = 2
     */
    rank: number;
}
/**
 * @generated from protobuf enum polycentric.v2.SortUsersBy
 */
export enum SortUsersBy {
    /**
     * Default sorting by relevancy.
     *
     * @generated from protobuf enum value: SORT_USERS_BY_DEFAULT = 0;
     */
    DEFAULT = 0,
    /**
     * Alphabetic order of profile name.
     *
     * TODO: determine how to determine popularity.
     * SORT_USERS_BY_POPULAR = 2;
     *
     * @generated from protobuf enum value: SORT_USERS_BY_ALPHA = 1;
     */
    ALPHA = 1
}
/**
 * @generated from protobuf enum polycentric.v2.SortPostsBy
 */
export enum SortPostsBy {
    /**
     * Default sorting by relevancy.
     *
     * @generated from protobuf enum value: SORT_POSTS_BY_DEFAULT = 0;
     */
    DEFAULT = 0,
    /**
     * Top post first.
     *
     * @generated from protobuf enum value: SORT_POSTS_BY_TOP = 1;
     */
    TOP = 1,
    /**
     * / Latests post first.
     *
     * @generated from protobuf enum value: SORT_POSTS_BY_LATEST = 2;
     */
    LATEST = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class SearchUsersRequest$Type extends MessageType<SearchUsersRequest> {
    constructor() {
        super("polycentric.v2.SearchUsersRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sort_by", kind: "enum", opt: true, T: () => ["polycentric.v2.SortUsersBy", SortUsersBy, "SORT_USERS_BY_"] },
            { no: 3, name: "page_params", kind: "message", T: () => PageParams }
        ]);
    }
    create(value?: PartialMessage<SearchUsersRequest>): SearchUsersRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.query = "";
        if (value !== undefined)
            reflectionMergePartial<SearchUsersRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchUsersRequest): SearchUsersRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                case /* optional polycentric.v2.SortUsersBy sort_by */ 2:
                    message.sortBy = reader.int32();
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 3:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchUsersRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        /* optional polycentric.v2.SortUsersBy sort_by = 2; */
        if (message.sortBy !== undefined)
            writer.tag(2, WireType.Varint).int32(message.sortBy);
        /* optional polycentric.v2.PageParams page_params = 3; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SearchUsersRequest
 */
export const SearchUsersRequest = new SearchUsersRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchPostsRequest$Type extends MessageType<SearchPostsRequest> {
    constructor() {
        super("polycentric.v2.SearchPostsRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sort_by", kind: "enum", opt: true, T: () => ["polycentric.v2.SortPostsBy", SortPostsBy, "SORT_POSTS_BY_"] },
            { no: 3, name: "page_params", kind: "message", T: () => PageParams },
            { no: 4, name: "omit_labels", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchPostsRequest>): SearchPostsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.query = "";
        message.omitLabels = [];
        if (value !== undefined)
            reflectionMergePartial<SearchPostsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchPostsRequest): SearchPostsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                case /* optional polycentric.v2.SortPostsBy sort_by */ 2:
                    message.sortBy = reader.int32();
                    break;
                case /* optional polycentric.v2.PageParams page_params */ 3:
                    message.pageParams = PageParams.internalBinaryRead(reader, reader.uint32(), options, message.pageParams);
                    break;
                case /* repeated string omit_labels */ 4:
                    message.omitLabels.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchPostsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        /* optional polycentric.v2.SortPostsBy sort_by = 2; */
        if (message.sortBy !== undefined)
            writer.tag(2, WireType.Varint).int32(message.sortBy);
        /* optional polycentric.v2.PageParams page_params = 3; */
        if (message.pageParams)
            PageParams.internalBinaryWrite(message.pageParams, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated string omit_labels = 4; */
        for (let i = 0; i < message.omitLabels.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.omitLabels[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SearchPostsRequest
 */
export const SearchPostsRequest = new SearchPostsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchUsersResponse$Type extends MessageType<SearchUsersResponse> {
    constructor() {
        super("polycentric.v2.SearchUsersResponse", [
            { no: 1, name: "results", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SearchResult },
            { no: 2, name: "page_info", kind: "message", T: () => PageInfo },
            { no: 3, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint }
        ]);
    }
    create(value?: PartialMessage<SearchUsersResponse>): SearchUsersResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.results = [];
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<SearchUsersResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchUsersResponse): SearchUsersResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.SearchResult results */ 1:
                    message.results.push(SearchResult.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional polycentric.v2.PageInfo page_info */ 2:
                    message.pageInfo = PageInfo.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 3:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchUsersResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.SearchResult results = 1; */
        for (let i = 0; i < message.results.length; i++)
            SearchResult.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.PageInfo page_info = 2; */
        if (message.pageInfo)
            PageInfo.internalBinaryWrite(message.pageInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 3; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SearchUsersResponse
 */
export const SearchUsersResponse = new SearchUsersResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchPostsResponse$Type extends MessageType<SearchPostsResponse> {
    constructor() {
        super("polycentric.v2.SearchPostsResponse", [
            { no: 1, name: "results", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => SearchResult },
            { no: 2, name: "page_info", kind: "message", T: () => PageInfo },
            { no: 3, name: "event_hints", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventHint }
        ]);
    }
    create(value?: PartialMessage<SearchPostsResponse>): SearchPostsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.results = [];
        message.eventHints = [];
        if (value !== undefined)
            reflectionMergePartial<SearchPostsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchPostsResponse): SearchPostsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.SearchResult results */ 1:
                    message.results.push(SearchResult.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional polycentric.v2.PageInfo page_info */ 2:
                    message.pageInfo = PageInfo.internalBinaryRead(reader, reader.uint32(), options, message.pageInfo);
                    break;
                case /* repeated polycentric.v2.EventHint event_hints */ 3:
                    message.eventHints.push(EventHint.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchPostsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.SearchResult results = 1; */
        for (let i = 0; i < message.results.length; i++)
            SearchResult.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional polycentric.v2.PageInfo page_info = 2; */
        if (message.pageInfo)
            PageInfo.internalBinaryWrite(message.pageInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated polycentric.v2.EventHint event_hints = 3; */
        for (let i = 0; i < message.eventHints.length; i++)
            EventHint.internalBinaryWrite(message.eventHints[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SearchPostsResponse
 */
export const SearchPostsResponse = new SearchPostsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchResult$Type extends MessageType<SearchResult> {
    constructor() {
        super("polycentric.v2.SearchResult", [
            { no: 1, name: "event_bundle", kind: "message", T: () => EventBundle },
            { no: 2, name: "rank", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<SearchResult>): SearchResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rank = 0;
        if (value !== undefined)
            reflectionMergePartial<SearchResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchResult): SearchResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventBundle event_bundle */ 1:
                    message.eventBundle = EventBundle.internalBinaryRead(reader, reader.uint32(), options, message.eventBundle);
                    break;
                case /* float rank */ 2:
                    message.rank = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventBundle event_bundle = 1; */
        if (message.eventBundle)
            EventBundle.internalBinaryWrite(message.eventBundle, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* float rank = 2; */
        if (message.rank !== 0)
            writer.tag(2, WireType.Bit32).float(message.rank);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SearchResult
 */
export const SearchResult = new SearchResult$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.SearchService
 */
export const SearchService = new ServiceType("polycentric.v2.SearchService", [
    { name: "SearchUsers", options: {}, I: SearchUsersRequest, O: SearchUsersResponse },
    { name: "SearchPosts", options: {}, I: SearchPostsRequest, O: SearchPostsResponse }
]);
