// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/server.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * *
 * Current version the server is running on.
 *
 * @generated from protobuf message polycentric.v2.ServerVersion
 */
export interface ServerVersion {
    /**
     * @generated from protobuf field: string version = 1
     */
    version: string;
}
/**
 * *
 * Relevant information about the current server, such as version, public endpoints, etc.
 *
 * @generated from protobuf message polycentric.v2.ServerInfo
 */
export interface ServerInfo {
    /**
     * @generated from protobuf field: polycentric.v2.ServerVersion version = 1
     */
    version?: ServerVersion;
    /**
     * URL used to resolve HTTP assets (blobs, images, etc)
     *
     * @generated from protobuf field: string cdn_url = 2
     */
    cdnUrl: string;
}
/**
 * @generated from protobuf message polycentric.v2.GetServerInfoRequest
 */
export interface GetServerInfoRequest {
}
/**
 * @generated from protobuf message polycentric.v2.GetServerInfoResponse
 */
export interface GetServerInfoResponse {
    /**
     * @generated from protobuf field: polycentric.v2.ServerInfo server_info = 1
     */
    serverInfo?: ServerInfo;
}
// @generated message type with reflection information, may provide speed optimized methods
class ServerVersion$Type extends MessageType<ServerVersion> {
    constructor() {
        super("polycentric.v2.ServerVersion", [
            { no: 1, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ServerVersion>): ServerVersion {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.version = "";
        if (value !== undefined)
            reflectionMergePartial<ServerVersion>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerVersion): ServerVersion {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string version */ 1:
                    message.version = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerVersion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string version = 1; */
        if (message.version !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.version);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ServerVersion
 */
export const ServerVersion = new ServerVersion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerInfo$Type extends MessageType<ServerInfo> {
    constructor() {
        super("polycentric.v2.ServerInfo", [
            { no: 1, name: "version", kind: "message", T: () => ServerVersion },
            { no: 2, name: "cdn_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ServerInfo>): ServerInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cdnUrl = "";
        if (value !== undefined)
            reflectionMergePartial<ServerInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerInfo): ServerInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.ServerVersion version */ 1:
                    message.version = ServerVersion.internalBinaryRead(reader, reader.uint32(), options, message.version);
                    break;
                case /* string cdn_url */ 2:
                    message.cdnUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.ServerVersion version = 1; */
        if (message.version)
            ServerVersion.internalBinaryWrite(message.version, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string cdn_url = 2; */
        if (message.cdnUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.cdnUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ServerInfo
 */
export const ServerInfo = new ServerInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetServerInfoRequest$Type extends MessageType<GetServerInfoRequest> {
    constructor() {
        super("polycentric.v2.GetServerInfoRequest", []);
    }
    create(value?: PartialMessage<GetServerInfoRequest>): GetServerInfoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetServerInfoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetServerInfoRequest): GetServerInfoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetServerInfoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetServerInfoRequest
 */
export const GetServerInfoRequest = new GetServerInfoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetServerInfoResponse$Type extends MessageType<GetServerInfoResponse> {
    constructor() {
        super("polycentric.v2.GetServerInfoResponse", [
            { no: 1, name: "server_info", kind: "message", T: () => ServerInfo }
        ]);
    }
    create(value?: PartialMessage<GetServerInfoResponse>): GetServerInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetServerInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetServerInfoResponse): GetServerInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.ServerInfo server_info */ 1:
                    message.serverInfo = ServerInfo.internalBinaryRead(reader, reader.uint32(), options, message.serverInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetServerInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.ServerInfo server_info = 1; */
        if (message.serverInfo)
            ServerInfo.internalBinaryWrite(message.serverInfo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.GetServerInfoResponse
 */
export const GetServerInfoResponse = new GetServerInfoResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.ServerService
 */
export const ServerService = new ServiceType("polycentric.v2.ServerService", [
    { name: "GetInfo", options: {}, I: GetServerInfoRequest, O: GetServerInfoResponse }
]);
