// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/server.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ServerService } from "./server";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetServerInfoResponse } from "./server";
import type { GetServerInfoRequest } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service polycentric.v2.ServerService
 */
export interface IServerServiceClient {
    /**
     * Returns relevant information about a server
     *
     * @generated from protobuf rpc: GetInfo
     */
    getInfo(input: GetServerInfoRequest, options?: RpcOptions): UnaryCall<GetServerInfoRequest, GetServerInfoResponse>;
}
/**
 * @generated from protobuf service polycentric.v2.ServerService
 */
export class ServerServiceClient implements IServerServiceClient, ServiceInfo {
    typeName = ServerService.typeName;
    methods = ServerService.methods;
    options = ServerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Returns relevant information about a server
     *
     * @generated from protobuf rpc: GetInfo
     */
    getInfo(input: GetServerInfoRequest, options?: RpcOptions): UnaryCall<GetServerInfoRequest, GetServerInfoResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetServerInfoRequest, GetServerInfoResponse>("unary", this._transport, method, opt, input);
    }
}
