// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/verifications.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { EventKey } from "./event_key";
import { ContentDigest } from "./common";
/**
 * Schema that defines the verification
 * These are self describing schemas and are intended to be specified in
 * a `VerificationClaim`.
 *
 * @generated from protobuf message polycentric.v2.VerificationSchema
 */
export interface VerificationSchema {
    /**
     * Human readable name of the schema (ie. X Verification).
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: repeated polycentric.v2.FieldDef fields = 3
     */
    fields: FieldDef[];
}
/**
 * @generated from protobuf message polycentric.v2.FieldDef
 */
export interface FieldDef {
    /**
     * Key used in VerificationClaim.fields, e.g. "handle", "proof_url".
     *
     * @generated from protobuf field: string key = 1
     */
    key: string;
    /**
     * How to decode this field's bytes.
     *
     * @generated from protobuf field: polycentric.v2.FieldKind kind = 2
     */
    kind: FieldKind;
    /**
     * Semantic refinement of kind: "url", "email", "iso8601-date", "hex".
     * Free-form so new formats need no proto change.
     *
     * @generated from protobuf field: string format = 3
     */
    format: string;
    /**
     * @generated from protobuf field: bool required = 4
     */
    required: boolean;
    /**
     * @generated from protobuf field: string description = 5
     */
    description: string;
    /**
     * @generated from protobuf field: optional string regex = 6
     */
    regex?: string;
    /**
     * @generated from protobuf field: optional uint32 max_len = 7
     */
    maxLen?: number;
}
/**
 * Protobuf serialization is non-deteministic. We hash the serialized schema
 * so we have the canonical hash - this aids with grouping of claims.
 *
 * @generated from protobuf message polycentric.v2.SerializedVerificationSchema
 */
export interface SerializedVerificationSchema {
    /**
     * Serialized VerificationSchema.
     *
     * @generated from protobuf field: bytes schema_bytes = 1
     */
    schemaBytes: Uint8Array;
    /**
     * Digest over schema_bytes. Verify digest == hash(schema_bytes).
     *
     * @generated from protobuf field: polycentric.v2.ContentDigest digest = 2
     */
    digest?: ContentDigest;
}
/**
 * Claim a user makes
 *
 * @generated from protobuf message polycentric.v2.VerificationClaim
 */
export interface VerificationClaim {
    /**
     * The schema this claim instantiates, carried inline.
     *
     * @generated from protobuf field: polycentric.v2.SerializedVerificationSchema schema = 1
     */
    schema?: SerializedVerificationSchema;
    /**
     * Values keyed by FieldDef.key, decoded per the schema's FieldKind.
     *
     * @generated from protobuf field: map<string, bytes> fields = 2
     */
    fields: {
        [key: string]: Uint8Array;
    };
}
/**
 * Targets a claim at one or more identities. Separate from the claim so
 * targeting can be set (or changed) after the claim is created.
 *
 * @generated from protobuf message polycentric.v2.VerificationTarget
 */
export interface VerificationTarget {
    /**
     * The claim event being targeted.
     *
     * @generated from protobuf field: polycentric.v2.EventKey claim_event_key = 1
     */
    claimEventKey?: EventKey;
    /**
     * Identities the claim is intended for.
     *
     * @generated from protobuf field: repeated string target_identities = 2
     */
    targetIdentities: string[];
}
/**
 * ── A verification of a claim ──
 *
 * @generated from protobuf message polycentric.v2.VerificationVerify
 */
export interface VerificationVerify {
    /**
     * The claim event being verified. The event's author is the verifier.
     *
     * @generated from protobuf field: polycentric.v2.EventKey claim_event_key = 1
     */
    claimEventKey?: EventKey;
}
/**
 * Canonical byte encoding per kind (claims are hashed, so reject non-canonical):
 *   STRING -> UTF-8        INT   -> int64 little-endian, 8 bytes
 *   BOOL   -> 0x00 / 0x01  BYTES -> verbatim
 *
 * @generated from protobuf enum polycentric.v2.FieldKind
 */
export enum FieldKind {
    /**
     * @generated from protobuf enum value: FIELD_KIND_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: FIELD_KIND_STRING = 1;
     */
    STRING = 1,
    /**
     * @generated from protobuf enum value: FIELD_KIND_INT = 2;
     */
    INT = 2,
    /**
     * @generated from protobuf enum value: FIELD_KIND_BOOL = 3;
     */
    BOOL = 3,
    /**
     * @generated from protobuf enum value: FIELD_KIND_BYTES = 4;
     */
    BYTES = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class VerificationSchema$Type extends MessageType<VerificationSchema> {
    constructor() {
        super("polycentric.v2.VerificationSchema", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "fields", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FieldDef }
        ]);
    }
    create(value?: PartialMessage<VerificationSchema>): VerificationSchema {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.description = "";
        message.fields = [];
        if (value !== undefined)
            reflectionMergePartial<VerificationSchema>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VerificationSchema): VerificationSchema {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* repeated polycentric.v2.FieldDef fields */ 3:
                    message.fields.push(FieldDef.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VerificationSchema, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* repeated polycentric.v2.FieldDef fields = 3; */
        for (let i = 0; i < message.fields.length; i++)
            FieldDef.internalBinaryWrite(message.fields[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.VerificationSchema
 */
export const VerificationSchema = new VerificationSchema$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FieldDef$Type extends MessageType<FieldDef> {
    constructor() {
        super("polycentric.v2.FieldDef", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "kind", kind: "enum", T: () => ["polycentric.v2.FieldKind", FieldKind, "FIELD_KIND_"] },
            { no: 3, name: "format", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "required", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "regex", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "max_len", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<FieldDef>): FieldDef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.key = "";
        message.kind = 0;
        message.format = "";
        message.required = false;
        message.description = "";
        if (value !== undefined)
            reflectionMergePartial<FieldDef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FieldDef): FieldDef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string key */ 1:
                    message.key = reader.string();
                    break;
                case /* polycentric.v2.FieldKind kind */ 2:
                    message.kind = reader.int32();
                    break;
                case /* string format */ 3:
                    message.format = reader.string();
                    break;
                case /* bool required */ 4:
                    message.required = reader.bool();
                    break;
                case /* string description */ 5:
                    message.description = reader.string();
                    break;
                case /* optional string regex */ 6:
                    message.regex = reader.string();
                    break;
                case /* optional uint32 max_len */ 7:
                    message.maxLen = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FieldDef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string key = 1; */
        if (message.key !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.key);
        /* polycentric.v2.FieldKind kind = 2; */
        if (message.kind !== 0)
            writer.tag(2, WireType.Varint).int32(message.kind);
        /* string format = 3; */
        if (message.format !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.format);
        /* bool required = 4; */
        if (message.required !== false)
            writer.tag(4, WireType.Varint).bool(message.required);
        /* string description = 5; */
        if (message.description !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.description);
        /* optional string regex = 6; */
        if (message.regex !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.regex);
        /* optional uint32 max_len = 7; */
        if (message.maxLen !== undefined)
            writer.tag(7, WireType.Varint).uint32(message.maxLen);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.FieldDef
 */
export const FieldDef = new FieldDef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SerializedVerificationSchema$Type extends MessageType<SerializedVerificationSchema> {
    constructor() {
        super("polycentric.v2.SerializedVerificationSchema", [
            { no: 1, name: "schema_bytes", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "digest", kind: "message", T: () => ContentDigest }
        ]);
    }
    create(value?: PartialMessage<SerializedVerificationSchema>): SerializedVerificationSchema {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.schemaBytes = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SerializedVerificationSchema>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SerializedVerificationSchema): SerializedVerificationSchema {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes schema_bytes */ 1:
                    message.schemaBytes = reader.bytes();
                    break;
                case /* polycentric.v2.ContentDigest digest */ 2:
                    message.digest = ContentDigest.internalBinaryRead(reader, reader.uint32(), options, message.digest);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SerializedVerificationSchema, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes schema_bytes = 1; */
        if (message.schemaBytes.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.schemaBytes);
        /* polycentric.v2.ContentDigest digest = 2; */
        if (message.digest)
            ContentDigest.internalBinaryWrite(message.digest, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.SerializedVerificationSchema
 */
export const SerializedVerificationSchema = new SerializedVerificationSchema$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VerificationClaim$Type extends MessageType<VerificationClaim> {
    constructor() {
        super("polycentric.v2.VerificationClaim", [
            { no: 1, name: "schema", kind: "message", T: () => SerializedVerificationSchema },
            { no: 2, name: "fields", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 12 /*ScalarType.BYTES*/ } }
        ]);
    }
    create(value?: PartialMessage<VerificationClaim>): VerificationClaim {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fields = {};
        if (value !== undefined)
            reflectionMergePartial<VerificationClaim>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VerificationClaim): VerificationClaim {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.SerializedVerificationSchema schema */ 1:
                    message.schema = SerializedVerificationSchema.internalBinaryRead(reader, reader.uint32(), options, message.schema);
                    break;
                case /* map<string, bytes> fields */ 2:
                    this.binaryReadMap2(message.fields, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: VerificationClaim["fields"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof VerificationClaim["fields"] | undefined, val: VerificationClaim["fields"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.bytes();
                    break;
                default: throw new globalThis.Error("unknown map entry field for polycentric.v2.VerificationClaim.fields");
            }
        }
        map[key ?? ""] = val ?? new Uint8Array(0);
    }
    internalBinaryWrite(message: VerificationClaim, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.SerializedVerificationSchema schema = 1; */
        if (message.schema)
            SerializedVerificationSchema.internalBinaryWrite(message.schema, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* map<string, bytes> fields = 2; */
        for (let k of globalThis.Object.keys(message.fields))
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).bytes(message.fields[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.VerificationClaim
 */
export const VerificationClaim = new VerificationClaim$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VerificationTarget$Type extends MessageType<VerificationTarget> {
    constructor() {
        super("polycentric.v2.VerificationTarget", [
            { no: 1, name: "claim_event_key", kind: "message", T: () => EventKey },
            { no: 2, name: "target_identities", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<VerificationTarget>): VerificationTarget {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.targetIdentities = [];
        if (value !== undefined)
            reflectionMergePartial<VerificationTarget>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VerificationTarget): VerificationTarget {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey claim_event_key */ 1:
                    message.claimEventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.claimEventKey);
                    break;
                case /* repeated string target_identities */ 2:
                    message.targetIdentities.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VerificationTarget, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey claim_event_key = 1; */
        if (message.claimEventKey)
            EventKey.internalBinaryWrite(message.claimEventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated string target_identities = 2; */
        for (let i = 0; i < message.targetIdentities.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.targetIdentities[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.VerificationTarget
 */
export const VerificationTarget = new VerificationTarget$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VerificationVerify$Type extends MessageType<VerificationVerify> {
    constructor() {
        super("polycentric.v2.VerificationVerify", [
            { no: 1, name: "claim_event_key", kind: "message", T: () => EventKey }
        ]);
    }
    create(value?: PartialMessage<VerificationVerify>): VerificationVerify {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<VerificationVerify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VerificationVerify): VerificationVerify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polycentric.v2.EventKey claim_event_key */ 1:
                    message.claimEventKey = EventKey.internalBinaryRead(reader, reader.uint32(), options, message.claimEventKey);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VerificationVerify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polycentric.v2.EventKey claim_event_key = 1; */
        if (message.claimEventKey)
            EventKey.internalBinaryWrite(message.claimEventKey, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.VerificationVerify
 */
export const VerificationVerify = new VerificationVerify$Type();
