// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/verifications_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { EventBundle } from "./events";
// Separate from verifications.proto: that file is imported by content.proto,
// so importing events.proto (for EventBundle) there would be a cyclic import.

/**
 * @generated from protobuf message polycentric.v2.ListClaimsRequest
 */
export interface ListClaimsRequest {
    /**
     * @generated from protobuf field: string claimed_by_identity = 1
     */
    claimedByIdentity: string;
}
/**
 * @generated from protobuf message polycentric.v2.ListClaimsResponse
 */
export interface ListClaimsResponse {
    /**
     * @generated from protobuf field: repeated polycentric.v2.EventBundle event_bundles = 1
     */
    eventBundles: EventBundle[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ListClaimsRequest$Type extends MessageType<ListClaimsRequest> {
    constructor() {
        super("polycentric.v2.ListClaimsRequest", [
            { no: 1, name: "claimed_by_identity", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListClaimsRequest>): ListClaimsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.claimedByIdentity = "";
        if (value !== undefined)
            reflectionMergePartial<ListClaimsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListClaimsRequest): ListClaimsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string claimed_by_identity */ 1:
                    message.claimedByIdentity = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListClaimsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string claimed_by_identity = 1; */
        if (message.claimedByIdentity !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.claimedByIdentity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListClaimsRequest
 */
export const ListClaimsRequest = new ListClaimsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListClaimsResponse$Type extends MessageType<ListClaimsResponse> {
    constructor() {
        super("polycentric.v2.ListClaimsResponse", [
            { no: 1, name: "event_bundles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => EventBundle }
        ]);
    }
    create(value?: PartialMessage<ListClaimsResponse>): ListClaimsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventBundles = [];
        if (value !== undefined)
            reflectionMergePartial<ListClaimsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListClaimsResponse): ListClaimsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polycentric.v2.EventBundle event_bundles */ 1:
                    message.eventBundles.push(EventBundle.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListClaimsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polycentric.v2.EventBundle event_bundles = 1; */
        for (let i = 0; i < message.eventBundles.length; i++)
            EventBundle.internalBinaryWrite(message.eventBundles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polycentric.v2.ListClaimsResponse
 */
export const ListClaimsResponse = new ListClaimsResponse$Type();
/**
 * @generated ServiceType for protobuf service polycentric.v2.VerificationsService
 */
export const VerificationsService = new ServiceType("polycentric.v2.VerificationsService", [
    { name: "ListClaims", options: {}, I: ListClaimsRequest, O: ListClaimsResponse }
]);
