// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "polycentric/v2/verifications_service.proto" (package "polycentric.v2", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { VerificationsService } from "./verifications_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListClaimsResponse } from "./verifications_service";
import type { ListClaimsRequest } from "./verifications_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service polycentric.v2.VerificationsService
 */
export interface IVerificationsServiceClient {
    /**
     * List the verification claims created by an identity.
     *
     * @generated from protobuf rpc: ListClaims
     */
    listClaims(input: ListClaimsRequest, options?: RpcOptions): UnaryCall<ListClaimsRequest, ListClaimsResponse>;
}
/**
 * @generated from protobuf service polycentric.v2.VerificationsService
 */
export class VerificationsServiceClient implements IVerificationsServiceClient, ServiceInfo {
    typeName = VerificationsService.typeName;
    methods = VerificationsService.methods;
    options = VerificationsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * List the verification claims created by an identity.
     *
     * @generated from protobuf rpc: ListClaims
     */
    listClaims(input: ListClaimsRequest, options?: RpcOptions): UnaryCall<ListClaimsRequest, ListClaimsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListClaimsRequest, ListClaimsResponse>("unary", this._transport, method, opt, input);
    }
}
