[package]
name = "integration-tests"
version = "0.0.1"
edition = "2024"
publish = false

[lib]
name = "integration_tests"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "src/tests.rs"

[dependencies]
entity = { path = "../entity" }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
prost = "0.14"
rand = "0.8"
sha2 = "0.10"
sea-orm = { version = "~2.0.0-rc.37", features = ["sqlx-postgres", "runtime-tokio"] }
tokio = { version = "1", features = ["full"] }
tonic = "*"
tonic-prost = "*"

[build-dependencies]
tonic-prost-build = "*"
