[package]
name = "integration-tests"
version = "0.0.1"
edition = "2024"
publish = false

[lib]
name = "integration_tests"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "src/tests.rs"

[dependencies]
entity = { path = "../entity" }
ed25519-dalek.workspace = true
getrandom.workspace = true
prost = "0.14"
sha2 = "0.10"
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio"] }
tokio = { workspace = true, features = ["full"] }
tonic = "*"
tonic-prost = "*"
rand = { version = "0.10", default-features = false, features = ["std", "std_rng", "thread_rng"] }

[build-dependencies]
tonic-prost-build = "*"
