[package]
name = "server"
version = "0.0.1"
edition = "2024"

[dependencies]
# Workspace
entity = { path = "./entity" }
# 3rd Party
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
axum = { version = "0.8.8", features = ["http2"] }
ed25519-dalek = "2.2.0"
log = "0.4"
polycentric-common = { path = "../../packages/rs-common" }
prost = "0.14"
prost-types = "0.14"
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-postgres", "runtime-tokio", "macros", "mock" ] }
sha2 = "0.10"
time = "0.3"
tokio = { version = "1.50.0", features = ["full"] }
tonic = "*"
tonic-prost = "*"
tonic-reflection = "*"
tonic-web = "*"
tower-http = { version = "*", features = ["cors"] }
tower-layer = "*"
http = "*"

