syntax = "proto3";
package polycentric.v2;

import "polycentric/v2/event_key.proto";
import "polycentric/v2/identity.proto";

enum ContentDigestType {
  CONTENT_DIGEST_TYPE_UNSPECIFIED = 0;
  CONTENT_DIGEST_TYPE_SHA256 = 1;
}

message ContentDigest {
  ContentDigestType type = 1;
  // We hash the serialized bytes
  bytes value = 2;
}

// Content of the event
message Content {
  oneof content_body {
    Post post = 2;
    Delete delete = 3;
    Follow follow = 4;
    Block block = 5;
    Reaction reaction = 6;
    ProfileUpdate profile_update = 7;
    Identity identity = 8;
    Repost repost = 9;
  }
}

// Serialized content. This is what we do the ContentDigest / Checksum on.
message SerializedContent {
  bytes content_bytes = 1;
}

message Post {
  // Main text content of the post
  string text = 1;
  optional PostReply reply = 2;
  // Multiple images
  repeated ImageSet images = 3;
  optional EventKey quote = 4;
}

message PostReply {
  // Initial post in the reply chain.
  EventKey root = 1;
  // Post that is being replied to
  EventKey parent = 2;
}

message Repost {
  optional EventKey post = 1;
}

// When processed by a server it should check if the data is referenced by any events
// If the Content is linked elswhere, the DELETE is ignored and the server should keep the data.
// If the Content is not linked elsewhere then it can be deleted / purged by the server.
// Essentially, a DELETE means; Ignore (or forget about) the contents of a previous event.
message Delete {
  // Event key to be deleted
  EventKey event_key = 1;
}

message Follow {
  string identity = 1;
}

message Block {
  string identity = 1;
}

message Reaction {
  // Key of the event being reacted to
  EventKey event_key = 1;
  // Optional emoji
  optional string emoji = 2;
  // Upvote = true. Downvote = false.
  bool positive = 3;
}

message ProfileUpdate {
  // A friendly display name for the user
  optional string name = 1;
  // Reference to the Blob for the avatar (support multiple different sizes)
  optional ImageSet avatar = 2;
  // Reference to the Blob of a banner (support multiple different sizes)
  optional ImageSet banner = 3;
  // Bio
  optional string description = 4;
}

// If an uploaded Blob is uploaded to the servers Object Storage and not
// then attached added to the Content repository, the server will delete from Object Storage.
message Blob {
  // Digest/Checksum of the blob
  ContentDigest digest = 1;
  string mime_type = 2;
  int64 size = 3;
}

// Single image with reference to the blob
message Image {
  Blob blob = 1;
  int32 width = 2;
  int32 height = 3;
}

// Collection of different variants of an image
message ImageSet {
  repeated Image images = 1;
}

/**
 * gRPC requests
 */
message SyncContentRequest {
  // Digest that was created from the serialized content_bytes
  ContentDigest digest = 1;
  // Serialized Content message
  bytes content_bytes = 2;
}

message SyncContentResponse {}

/**
 * Request message for upoading a blob
 */
message UploadBlobRequest {
  // Reference message of the blob (mime type, content digest).
  Blob blob = 1;
  // Body (content) of the blob
  bytes body = 2;
}

message UploadBlobResponse {}

service ContentService {
  // Synchronises events from a client to the server
  rpc SyncContent(SyncContentRequest) returns (SyncContentResponse);
  // Uploads a blob. If the blob is not referenced in a time window, it will be deleted.
  rpc UploadBlob(UploadBlobRequest) returns (UploadBlobResponse);
}
