syntax = "proto3";
package polycentric.v2;

import "polycentric/v2/content.proto";
import "polycentric/v2/event_key.proto";
import "polycentric/v2/keypair.proto";

// Contains the sequences that the current KeyPair is aware of. 
message VectorClock {
  repeated uint64 sequence = 1;
}

// Event messages reference, but do not include, content
message Event {
  // Key for the event
  EventKey key = 1;

  // Vector clock to keep the same collection on shared identities in sync
  // (collection, vector clock)
  map<int32, VectorClock> vector_clocks = 2;

  // Signature of the previous event signed by the same key. Assists in creating
  // immutable collections.
  bytes previous_signature = 3;

  // Digest of the content
  ContentDigest content_digest = 4;

  // Timestamp, in milliseconds, of when the event was created
  uint64 created_at = 5;
}

message SignedEvent {
  // Signature of events_bytes below (not the Event message)
  bytes signature = 1;
  // Serialized representation of the Event message that is signed against
  bytes event_bytes = 2;
}

// Bundle of the SignedEvent and SerializedContent messages
// We use SerializedContent so that the checksum of the content
// can be verified
message EventBundle {
  SignedEvent signed_event = 1;
  optional SerializedContent serialized_content = 2;
}

message ListEventsRequest {
  // Max number of events to return
  optional int32 limit = 1;
  // Collection to filter events by
  optional int32 collection = 2;
  // Identity key to filter events by
  optional string identity = 3;
  // Filter events to those signed by this public key
  optional PublicKey signed_by = 4;
}

message ListEventsResponse {
  repeated EventBundle event_bundles = 1;
  string previous_token = 2;
  string next_token = 3;
}

message PutEventsRequest {
  repeated EventBundle event_bundles = 1;
}

message PutEventsResponse {}

// Sync between clients and servers
service EventSyncService {
  // Returns a list of events (with content) from the server
  rpc ListEvents(ListEventsRequest) returns (ListEventsResponse);
  // Add events (with content) from a client to the server
  rpc PutEvents(PutEventsRequest) returns (PutEventsResponse);
}
