syntax = "proto3";
package polycentric.v2;

import "polycentric/v2/common.proto";
import "polycentric/v2/event_key.proto";
import "polycentric/v2/events.proto";

enum FeedAlgorithm {
  FEED_ALGORITHM_UNSPECIFIED = 0;
  FEED_ALGORITHM_FOLLOWING = 1;
  FEED_ALGORITHM_SUGGESTED = 2;
}

message GetIdentityFeedRequest {
  // Identity to return the posts of
  string identity = 1;
  optional PageParams page_params = 2;
  // Label values for which the requester does not want to see content
  repeated string omit_labels = 3;
}

message GetFollowingFeedRequest {
  // Identity of the follower to return the feed for
  string follower_identity = 1;
  optional PageParams page_params = 2;
  // Label values for which the requester does not want to see content
  repeated string omit_labels = 3;
}

message GetExploreFeedRequest {
  // Identity of the caller to return relevant posts fort
  optional string identity = 1;
  optional PageParams page_params = 2;
  // Label values for which the requester does not want to see content
  repeated string omit_labels = 3;
}

message GetFeedResponse {
  repeated EventBundle event_bundles = 1;
  repeated EventHint event_hints = 2;
  optional PageInfo page_info = 3;
}

message GetPostThreadResponse {
  repeated EventBundle thread = 1;
  repeated EventHint event_hints = 2;
}

message GetPostThreadRequest {
  // Parent post to return the thread for
  EventKey event_key = 1;
  int32 limit = 2;
}

/**
 * Curated feeds provided by servers
 */
service FeedsService {
  // Posts that belong to an identity
  rpc GetIdentityFeed(GetIdentityFeedRequest) returns (GetFeedResponse);
  //
  rpc GetFollowingFeed(GetFollowingFeedRequest) returns (GetFeedResponse);
  //
  rpc GetExploreFeed(GetExploreFeedRequest) returns (GetFeedResponse);
  // Replies to a post
  rpc GetPostThread(GetPostThreadRequest) returns (GetPostThreadResponse);
}
