syntax = "proto3";
package polycentric.v2;

import "polycentric/v2/common.proto";
import "polycentric/v2/events.proto";
import "polycentric/v2/server.proto";

message Notification {
  // Event that triggered the notification
  EventBundle trigger_event = 1;
  // Event that the notification is in relation to
  EventBundle subject_event = 2;
}

message GetNotificationsRequest {
  string identity = 1;
  // Return the 1 X number of notifications
  optional uint32 first = 2;
  // Return notifications after a cursor
  optional string after = 3;
}

message GetNotificationsResponse {
  repeated Notification notification = 1;
  // Events that help the client resolve with fewer network calls
  repeated EventHint event_hints = 2;
  PageInfo page_info = 3;
}

message RegisterPushNotificationRequest {
  string service = 1;
  string token = 2;
}

message RegisterPushNotificationResponse {}

message UnregisterPushNotificationRequest {
  string service = 1;
  string token = 2;
}

message UnregisterPushNotificationResponse {}

/**
 * Push notifications provided by polycentric servers
 */
service NotificationService {
  // This endpoint expects a signed RegisterPushNotificationRequest message
  rpc RegisterPushNotifications(SignedMessage) returns (RegisterPushNotificationResponse);

  // This endpoint expects a signed UnregisterPushNotificationRequest message
  rpc UnregisterPushNotifications(SignedMessage) returns (UnregisterPushNotificationResponse);
}
