name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync with Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/futo-org/polycentric.git
          git fetch upstream
          git checkout develop
          git merge upstream/develop --no-ff -m "Merge upstream develop" || (echo "Conflict detected, manual intervention required" && exit 1)
          git push origin develop